-- Migration 015: internal URL identity baseline and current-entity bindings.
--
-- Additive only. This migration performs no URL inventory, backfill, redirect,
-- canonical change, sitemap change, or public grant.

CREATE TABLE public.url_registry (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id                 TEXT NOT NULL DEFAULT 'appliance-repair-base',
    environment             TEXT NOT NULL,
    url                     TEXT NOT NULL,
    normalized_url          TEXT NOT NULL,
    path                    TEXT NOT NULL,
    page_type               TEXT NOT NULL,
    http_status             SMALLINT,
    canonical_url           TEXT,
    sitemap_present         BOOLEAN,
    internal_incoming_links INTEGER,
    search_impressions      BIGINT,
    search_clicks           BIGINT,
    classification          TEXT NOT NULL DEFAULT 'unclassified',
    classification_reason   TEXT,
    first_observed_at       TIMESTAMPTZ NOT NULL,
    last_observed_at        TIMESTAMPTZ NOT NULL,
    reviewed_at             TIMESTAMPTZ,
    reviewed_by             TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT url_registry_site_check
        CHECK (site_id = 'appliance-repair-base'),
    CONSTRAINT url_registry_environment_check
        CHECK (environment IN ('development', 'staging', 'production')),
    CONSTRAINT url_registry_http_status_check
        CHECK (http_status IS NULL OR http_status BETWEEN 100 AND 599),
    CONSTRAINT url_registry_page_type_check
        CHECK (page_type IN ('brand', 'category', 'model', 'product_code',
                             'error_code', 'fault', 'article', 'guide', 'static',
                             'unknown')),
    CONSTRAINT url_registry_classification_check
        CHECK (classification IN ('unclassified', 'retain_200',
                                   'retain_200_with_new_data_model',
                                   'redirect_301_exact_match', 'genuine_404',
                                   'manual_review')),
    CONSTRAINT url_registry_counts_check
        CHECK ((internal_incoming_links IS NULL OR internal_incoming_links >= 0)
           AND (search_impressions IS NULL OR search_impressions >= 0)
           AND (search_clicks IS NULL OR search_clicks >= 0)),
    CONSTRAINT url_registry_observation_order_check
        CHECK (last_observed_at >= first_observed_at),
    CONSTRAINT url_registry_url_nonblank_check
        CHECK (btrim(url) <> '' AND btrim(normalized_url) <> '' AND path LIKE '/%'),
    CONSTRAINT url_registry_site_environment_url_key
        UNIQUE (site_id, environment, normalized_url)
);

CREATE INDEX url_registry_scope_classification_idx
    ON public.url_registry (site_id, environment, classification);
CREATE INDEX url_registry_path_idx ON public.url_registry (path COLLATE "C");
CREATE INDEX url_registry_last_observed_idx
    ON public.url_registry (last_observed_at DESC);

CREATE TABLE public.entity_url_bindings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url_id          BIGINT NOT NULL REFERENCES public.url_registry(id) ON DELETE RESTRICT,
    brand_id        INTEGER REFERENCES public.brands(id) ON DELETE RESTRICT,
    category_id     INTEGER REFERENCES public.categories(id) ON DELETE RESTRICT,
    model_id        INTEGER REFERENCES public.models(id) ON DELETE RESTRICT,
    product_code_id INTEGER REFERENCES public.product_codes(id) ON DELETE RESTRICT,
    error_code_id   INTEGER REFERENCES public.error_codes(id) ON DELETE RESTRICT,
    fault_id        INTEGER REFERENCES public.faults(id) ON DELETE RESTRICT,
    article_id      INTEGER REFERENCES public.articles(id) ON DELETE RESTRICT,
    entity_key      TEXT GENERATED ALWAYS AS (
        CASE
            WHEN brand_id IS NOT NULL THEN 'brand:' || brand_id::text
            WHEN category_id IS NOT NULL THEN 'category:' || category_id::text
            WHEN model_id IS NOT NULL THEN 'model:' || model_id::text
            WHEN product_code_id IS NOT NULL THEN 'product_code:' || product_code_id::text
            WHEN error_code_id IS NOT NULL THEN 'error_code:' || error_code_id::text
            WHEN fault_id IS NOT NULL THEN 'fault:' || fault_id::text
            WHEN article_id IS NOT NULL THEN 'article:' || article_id::text
        END
    ) STORED,
    binding_role   TEXT NOT NULL,
    mapping_status TEXT NOT NULL DEFAULT 'candidate',
    valid_from     TIMESTAMPTZ NOT NULL,
    valid_to       TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT entity_url_bindings_one_target_check
        CHECK (num_nonnulls(brand_id, category_id, model_id, product_code_id,
                            error_code_id, fault_id, article_id) = 1),
    CONSTRAINT entity_url_bindings_role_check
        CHECK (binding_role IN ('primary', 'legacy', 'alternate', 'retained_variant')),
    CONSTRAINT entity_url_bindings_status_check
        CHECK (mapping_status IN ('candidate', 'verified', 'rejected', 'superseded')),
    CONSTRAINT entity_url_bindings_validity_check
        CHECK (valid_to IS NULL OR valid_to > valid_from),
    CONSTRAINT entity_url_bindings_identity_key
        UNIQUE (url_id, entity_key, valid_from)
);

CREATE UNIQUE INDEX entity_url_bindings_one_current_primary_uidx
    ON public.entity_url_bindings (url_id)
    WHERE valid_to IS NULL
      AND mapping_status = 'verified'
      AND binding_role = 'primary';
CREATE UNIQUE INDEX entity_url_bindings_one_current_candidate_uidx
    ON public.entity_url_bindings (url_id, entity_key)
    WHERE valid_to IS NULL
      AND mapping_status IN ('candidate', 'verified');
CREATE INDEX entity_url_bindings_entity_idx
    ON public.entity_url_bindings (entity_key, mapping_status);
CREATE INDEX entity_url_bindings_url_status_idx
    ON public.entity_url_bindings (url_id, mapping_status);

CREATE OR REPLACE FUNCTION public.touch_information_model_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $function$
BEGIN
    NEW.updated_at = statement_timestamp();
    RETURN NEW;
END
$function$;

REVOKE ALL ON FUNCTION public.touch_information_model_updated_at() FROM PUBLIC, anon, authenticated;

CREATE TRIGGER url_registry_touch_updated_at
BEFORE UPDATE ON public.url_registry
FOR EACH ROW EXECUTE FUNCTION public.touch_information_model_updated_at();

CREATE TRIGGER entity_url_bindings_touch_updated_at
BEFORE UPDATE ON public.entity_url_bindings
FOR EACH ROW EXECUTE FUNCTION public.touch_information_model_updated_at();

ALTER TABLE public.url_registry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.url_registry FORCE ROW LEVEL SECURITY;
ALTER TABLE public.entity_url_bindings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.entity_url_bindings FORCE ROW LEVEL SECURITY;

REVOKE ALL ON public.url_registry FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.entity_url_bindings FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.url_registry TO service_role;
GRANT SELECT, INSERT, UPDATE ON public.entity_url_bindings TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.url_registry_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.entity_url_bindings_id_seq TO service_role;

INSERT INTO public.schema_migrations (version, filename)
VALUES ('015', '015_url_registry_and_entity_bindings.sql')
ON CONFLICT (version) DO NOTHING;

NOTIFY pgrst, 'reload schema';
