-- Migration 016: additive information-model v1 foundation.
-- No business data is backfilled and no public URL behavior is changed.
BEGIN;

CREATE OR REPLACE FUNCTION public.set_information_model_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := statement_timestamp();
    RETURN NEW;
END
$$;

CREATE TABLE public.model_variants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id integer NOT NULL REFERENCES public.models(id) ON DELETE RESTRICT,
    variant_code text NOT NULL,
    normalized_variant_code text NOT NULL,
    market text,
    region text,
    description text,
    status text NOT NULL DEFAULT 'candidate',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT model_variants_normalized_code_nonblank CHECK (btrim(normalized_variant_code) <> ''),
    CONSTRAINT model_variants_status_check CHECK (status IN ('candidate','verified','rejected')),
    CONSTRAINT model_variants_model_code_key UNIQUE (model_id, normalized_variant_code)
);
CREATE INDEX model_variants_model_status_idx ON public.model_variants(model_id,status);
CREATE INDEX model_variants_normalized_code_idx ON public.model_variants(normalized_variant_code);

ALTER TABLE public.product_codes
    ADD COLUMN model_variant_id bigint NULL REFERENCES public.model_variants(id) ON DELETE SET NULL,
    ADD COLUMN normalized_code text NULL;
CREATE INDEX product_codes_variant_normalized_idx
    ON public.product_codes(model_variant_id,normalized_code)
    WHERE model_variant_id IS NOT NULL;

CREATE TABLE public.legacy_model_mapping (
    legacy_model_id integer PRIMARY KEY REFERENCES public.models(id) ON DELETE RESTRICT,
    canonical_model_id integer NOT NULL REFERENCES public.models(id) ON DELETE RESTRICT,
    model_variant_id bigint NULL REFERENCES public.model_variants(id) ON DELETE RESTRICT,
    mapping_status text NOT NULL,
    mapping_reason text NOT NULL,
    confidence smallint NOT NULL CHECK (confidence BETWEEN 0 AND 100),
    reviewed_at timestamptz,
    reviewed_by text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT legacy_model_mapping_status_check CHECK (mapping_status IN ('unchanged','mapped_to_main','mapped_to_variant','rejected_candidate')),
    CONSTRAINT legacy_model_mapping_variant_check CHECK ((mapping_status='mapped_to_variant')=(model_variant_id IS NOT NULL)),
    CONSTRAINT legacy_model_mapping_identity_check CHECK (
        (mapping_status IN ('unchanged','rejected_candidate') AND legacy_model_id=canonical_model_id)
        OR (mapping_status IN ('mapped_to_main','mapped_to_variant') AND legacy_model_id<>canonical_model_id)
    )
);
CREATE INDEX legacy_model_mapping_canonical_idx ON public.legacy_model_mapping(canonical_model_id);
CREATE INDEX legacy_model_mapping_variant_idx ON public.legacy_model_mapping(model_variant_id);
CREATE INDEX legacy_model_mapping_status_idx ON public.legacy_model_mapping(mapping_status);

CREATE TABLE public.legacy_model_mapping_candidates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_model_id integer NOT NULL REFERENCES public.models(id) ON DELETE RESTRICT,
    candidate_model_id integer NOT NULL REFERENCES public.models(id) ON DELETE RESTRICT,
    candidate_variant_code text,
    normalized_candidate_variant_code text,
    candidate_status text NOT NULL DEFAULT 'candidate',
    confidence smallint NOT NULL CHECK (confidence BETWEEN 0 AND 100),
    mapping_reason text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT legacy_model_candidates_status_check CHECK (candidate_status IN ('candidate','accepted','rejected')),
    CONSTRAINT legacy_model_candidates_key UNIQUE NULLS NOT DISTINCT
        (legacy_model_id,candidate_model_id,normalized_candidate_variant_code)
);
CREATE INDEX legacy_model_candidates_legacy_status_idx ON public.legacy_model_mapping_candidates(legacy_model_id,candidate_status);
CREATE INDEX legacy_model_candidates_candidate_idx ON public.legacy_model_mapping_candidates(candidate_model_id);

CREATE TABLE public.model_content_translations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id integer NOT NULL REFERENCES public.models(id) ON DELETE RESTRICT,
    locale text NOT NULL REFERENCES public.locales(code) ON DELETE RESTRICT,
    overview text,
    short_summary text,
    publication_status text NOT NULL DEFAULT 'draft',
    source_hash text,
    reviewed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT model_content_locale_check CHECK (locale ~ '^[a-z]{2}(-[A-Z]{2})?$'),
    CONSTRAINT model_content_status_check CHECK (publication_status IN ('draft','review','published','archived')),
    CONSTRAINT model_content_published_check CHECK (publication_status<>'published' OR COALESCE(NULLIF(btrim(overview),''),NULLIF(btrim(short_summary),'')) IS NOT NULL),
    CONSTRAINT model_content_model_locale_key UNIQUE(model_id,locale)
);
CREATE INDEX model_content_locale_status_idx ON public.model_content_translations(locale,publication_status,model_id);

CREATE TABLE public.error_code_translations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_code_id integer NOT NULL REFERENCES public.error_codes(id) ON DELETE RESTRICT,
    locale text NOT NULL REFERENCES public.locales(code) ON DELETE RESTRICT,
    title text NOT NULL CHECK (btrim(title)<>''),
    description text,
    first_checks jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(first_checks)='array'),
    publication_status text NOT NULL DEFAULT 'draft' CHECK (publication_status IN ('draft','review','published','archived')),
    source_hash text,
    reviewed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT error_code_translations_locale_check CHECK (locale ~ '^[a-z]{2}(-[A-Z]{2})?$'),
    CONSTRAINT error_code_translations_key UNIQUE(error_code_id,locale)
);
CREATE INDEX error_code_translations_locale_status_idx ON public.error_code_translations(locale,publication_status,error_code_id);

CREATE TABLE public.guides (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id integer NOT NULL REFERENCES public.categories(id) ON DELETE RESTRICT,
    brand_id integer NULL REFERENCES public.brands(id) ON DELETE RESTRICT,
    canonical_title text NOT NULL CHECK (btrim(canonical_title)<>''),
    default_difficulty text NULL CHECK (default_difficulty IS NULL OR default_difficulty IN ('easy','medium','advanced')),
    default_estimated_minutes integer NULL CHECK (default_estimated_minutes IS NULL OR default_estimated_minutes>0),
    safety_notes text,
    is_general boolean NOT NULL DEFAULT false,
    content_status text NOT NULL DEFAULT 'draft' CHECK (content_status IN ('draft','review','published','archived')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX guides_scope_status_idx ON public.guides(category_id,brand_id,content_status);
CREATE INDEX guides_status_idx ON public.guides(content_status);

CREATE TABLE public.guide_translations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guide_id bigint NOT NULL REFERENCES public.guides(id) ON DELETE RESTRICT,
    locale text NOT NULL REFERENCES public.locales(code) ON DELETE RESTRICT,
    slug text NOT NULL CHECK (btrim(slug)<>''),
    title text NOT NULL CHECK (btrim(title)<>''),
    short_description text,
    summary text,
    steps_json jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(steps_json)='array'),
    publication_status text NOT NULL DEFAULT 'draft' CHECK (publication_status IN ('draft','review','published','archived')),
    source_hash text,
    reviewed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT guide_translations_locale_check CHECK (locale ~ '^[a-z]{2}(-[A-Z]{2})?$'),
    CONSTRAINT guide_translations_published_steps CHECK (publication_status<>'published' OR jsonb_array_length(steps_json)>0),
    CONSTRAINT guide_translations_guide_locale_key UNIQUE(guide_id,locale),
    CONSTRAINT guide_translations_locale_slug_key UNIQUE(locale,slug)
);
CREATE INDEX guide_translations_locale_status_idx ON public.guide_translations(locale,publication_status);

CREATE TABLE public.sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url text NOT NULL CHECK (btrim(url)<>''),
    normalized_url text NOT NULL CHECK (btrim(normalized_url)<>''),
    source_type text NOT NULL CHECK (source_type IN ('manual','website','service_document','dataset','other')),
    publisher text,
    title text,
    published_at timestamptz,
    retrieved_at timestamptz NOT NULL,
    content_hash text NOT NULL CHECK (btrim(content_hash)<>''),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT sources_identity_key UNIQUE(normalized_url,content_hash)
);
CREATE INDEX sources_normalized_url_idx ON public.sources(normalized_url);
CREATE INDEX sources_retrieved_at_idx ON public.sources(retrieved_at);

CREATE TABLE public.source_evidence (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id bigint NOT NULL REFERENCES public.sources(id) ON DELETE RESTRICT,
    model_id integer REFERENCES public.models(id) ON DELETE RESTRICT,
    model_variant_id bigint REFERENCES public.model_variants(id) ON DELETE RESTRICT,
    product_code_id integer REFERENCES public.product_codes(id) ON DELETE RESTRICT,
    error_code_id integer REFERENCES public.error_codes(id) ON DELETE RESTRICT,
    fault_id integer REFERENCES public.faults(id) ON DELETE RESTRICT,
    article_id integer REFERENCES public.articles(id) ON DELETE RESTRICT,
    guide_id bigint REFERENCES public.guides(id) ON DELETE RESTRICT,
    model_content_translation_id bigint REFERENCES public.model_content_translations(id) ON DELETE RESTRICT,
    error_code_translation_id bigint REFERENCES public.error_code_translations(id) ON DELETE RESTRICT,
    fault_translation_id integer REFERENCES public.fault_translations(id) ON DELETE RESTRICT,
    guide_translation_id bigint REFERENCES public.guide_translations(id) ON DELETE RESTRICT,
    field_name text NOT NULL CHECK (btrim(field_name)<>''),
    source_locator text NOT NULL CHECK (btrim(source_locator)<>''),
    observed_value jsonb NOT NULL,
    confidence smallint NOT NULL CHECK (confidence BETWEEN 0 AND 100),
    verification_status text NOT NULL DEFAULT 'candidate' CHECK (verification_status IN ('candidate','verified','rejected','conflicted')),
    observed_at timestamptz NOT NULL,
    verified_at timestamptz,
    verified_by text,
    created_at timestamptz NOT NULL DEFAULT now(),
    target_key text GENERATED ALWAYS AS (
        CASE
            WHEN model_id IS NOT NULL THEN 'model:'||model_id::text
            WHEN model_variant_id IS NOT NULL THEN 'model_variant:'||model_variant_id::text
            WHEN product_code_id IS NOT NULL THEN 'product_code:'||product_code_id::text
            WHEN error_code_id IS NOT NULL THEN 'error_code:'||error_code_id::text
            WHEN fault_id IS NOT NULL THEN 'fault:'||fault_id::text
            WHEN article_id IS NOT NULL THEN 'article:'||article_id::text
            WHEN guide_id IS NOT NULL THEN 'guide:'||guide_id::text
            WHEN model_content_translation_id IS NOT NULL THEN 'model_content_translation:'||model_content_translation_id::text
            WHEN error_code_translation_id IS NOT NULL THEN 'error_code_translation:'||error_code_translation_id::text
            WHEN fault_translation_id IS NOT NULL THEN 'fault_translation:'||fault_translation_id::text
            WHEN guide_translation_id IS NOT NULL THEN 'guide_translation:'||guide_translation_id::text
        END
    ) STORED,
    CONSTRAINT source_evidence_one_target CHECK (num_nonnulls(model_id,model_variant_id,product_code_id,error_code_id,fault_id,article_id,guide_id,model_content_translation_id,error_code_translation_id,fault_translation_id,guide_translation_id)=1),
    CONSTRAINT source_evidence_verification_check CHECK ((verification_status='verified' AND verified_at IS NOT NULL AND NULLIF(btrim(verified_by),'') IS NOT NULL) OR (verification_status<>'verified' AND verified_at IS NULL AND verified_by IS NULL)),
    CONSTRAINT source_evidence_identity_key UNIQUE(source_id,target_key,field_name,source_locator,observed_at)
);
CREATE INDEX source_evidence_target_idx ON public.source_evidence(target_key,field_name,verification_status);
CREATE INDEX source_evidence_source_idx ON public.source_evidence(source_id);

CREATE TABLE public.article_guides (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id integer NOT NULL REFERENCES public.articles(id) ON DELETE RESTRICT,
    guide_id bigint NOT NULL REFERENCES public.guides(id) ON DELETE RESTRICT,
    is_primary boolean NOT NULL DEFAULT false,
    sort_order integer NOT NULL DEFAULT 1 CHECK (sort_order>0),
    relation_status text NOT NULL DEFAULT 'candidate' CHECK (relation_status IN ('candidate','verified','rejected')),
    source_evidence_id bigint REFERENCES public.source_evidence(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(article_id,guide_id)
);
CREATE UNIQUE INDEX article_guides_verified_primary_uidx ON public.article_guides(article_id) WHERE is_primary AND relation_status='verified';

CREATE TABLE public.guide_error_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guide_id bigint NOT NULL REFERENCES public.guides(id) ON DELETE RESTRICT,
    error_code_id integer NOT NULL REFERENCES public.error_codes(id) ON DELETE RESTRICT,
    is_primary boolean NOT NULL DEFAULT false, sort_order integer NOT NULL DEFAULT 1 CHECK(sort_order>0),
    relation_status text NOT NULL DEFAULT 'candidate' CHECK(relation_status IN ('candidate','verified','rejected')),
    confidence smallint NOT NULL CHECK(confidence BETWEEN 0 AND 100),
    source_evidence_id bigint REFERENCES public.source_evidence(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(guide_id,error_code_id)
);
CREATE INDEX guide_error_codes_subject_idx ON public.guide_error_codes(error_code_id);
CREATE INDEX guide_error_codes_guide_status_idx ON public.guide_error_codes(guide_id,relation_status);

CREATE TABLE public.guide_faults (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guide_id bigint NOT NULL REFERENCES public.guides(id) ON DELETE RESTRICT,
    fault_id integer NOT NULL REFERENCES public.faults(id) ON DELETE RESTRICT,
    is_primary boolean NOT NULL DEFAULT false, sort_order integer NOT NULL DEFAULT 1 CHECK(sort_order>0),
    relation_status text NOT NULL DEFAULT 'candidate' CHECK(relation_status IN ('candidate','verified','rejected')),
    confidence smallint NOT NULL CHECK(confidence BETWEEN 0 AND 100),
    source_evidence_id bigint REFERENCES public.source_evidence(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(guide_id,fault_id)
);
CREATE INDEX guide_faults_subject_idx ON public.guide_faults(fault_id);
CREATE INDEX guide_faults_guide_status_idx ON public.guide_faults(guide_id,relation_status);

CREATE TABLE public.guide_models (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guide_id bigint NOT NULL REFERENCES public.guides(id) ON DELETE RESTRICT,
    model_id integer NOT NULL REFERENCES public.models(id) ON DELETE RESTRICT,
    applicability text NOT NULL CHECK(applicability IN ('applies','does_not_apply')),
    relation_status text NOT NULL DEFAULT 'candidate' CHECK(relation_status IN ('candidate','verified','rejected')),
    confidence smallint NOT NULL CHECK(confidence BETWEEN 0 AND 100),
    source_evidence_id bigint REFERENCES public.source_evidence(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(guide_id,model_id)
);
CREATE INDEX guide_models_model_status_idx ON public.guide_models(model_id,relation_status,applicability);

CREATE TABLE public.error_code_model_overrides (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id integer NOT NULL REFERENCES public.models(id) ON DELETE RESTRICT,
    error_code_id integer NOT NULL REFERENCES public.error_codes(id) ON DELETE RESTRICT,
    applicability text NOT NULL CHECK(applicability IN ('applies','does_not_apply')),
    relation_status text NOT NULL DEFAULT 'candidate' CHECK(relation_status IN ('candidate','verified','rejected')),
    confidence smallint NOT NULL CHECK(confidence BETWEEN 0 AND 100),
    source_evidence_id bigint REFERENCES public.source_evidence(id) ON DELETE SET NULL,
    verified_at timestamptz, verified_by text, notes text,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT error_code_override_verified_check CHECK ((relation_status='verified' AND verified_at IS NOT NULL AND NULLIF(btrim(verified_by),'') IS NOT NULL) OR (relation_status<>'verified' AND verified_at IS NULL AND verified_by IS NULL)),
    UNIQUE(model_id,error_code_id)
);
CREATE INDEX error_code_override_model_status_idx ON public.error_code_model_overrides(model_id,relation_status,applicability);
CREATE INDEX error_code_override_subject_idx ON public.error_code_model_overrides(error_code_id);

CREATE TABLE public.fault_model_overrides (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id integer NOT NULL REFERENCES public.models(id) ON DELETE RESTRICT,
    fault_id integer NOT NULL REFERENCES public.faults(id) ON DELETE RESTRICT,
    applicability text NOT NULL CHECK(applicability IN ('applies','does_not_apply')),
    relation_status text NOT NULL DEFAULT 'candidate' CHECK(relation_status IN ('candidate','verified','rejected')),
    confidence smallint NOT NULL CHECK(confidence BETWEEN 0 AND 100),
    source_evidence_id bigint REFERENCES public.source_evidence(id) ON DELETE SET NULL,
    verified_at timestamptz, verified_by text, notes text,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fault_override_verified_check CHECK ((relation_status='verified' AND verified_at IS NOT NULL AND NULLIF(btrim(verified_by),'') IS NOT NULL) OR (relation_status<>'verified' AND verified_at IS NULL AND verified_by IS NULL)),
    UNIQUE(model_id,fault_id)
);
CREATE INDEX fault_override_model_status_idx ON public.fault_model_overrides(model_id,relation_status,applicability);
CREATE INDEX fault_override_subject_idx ON public.fault_model_overrides(fault_id);

CREATE TABLE public.url_redirects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_url_id bigint NOT NULL UNIQUE REFERENCES public.url_registry(id) ON DELETE RESTRICT,
    destination_url_id bigint NOT NULL REFERENCES public.url_registry(id) ON DELETE RESTRICT,
    status_code smallint NOT NULL DEFAULT 301 CHECK(status_code IN (301,308)),
    approval_status text NOT NULL CHECK(approval_status IN ('approved','activated','verified','rejected','rolled_back')),
    reason text NOT NULL CHECK(btrim(reason)<>''), migration_batch_id text NOT NULL CHECK(btrim(migration_batch_id)<>''),
    approved_at timestamptz, approved_by text, activated_at timestamptz, verified_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT url_redirects_distinct_check CHECK(source_url_id<>destination_url_id),
    CONSTRAINT url_redirects_approval_check CHECK ((approval_status IN ('approved','activated','verified') AND approved_at IS NOT NULL AND NULLIF(btrim(approved_by),'') IS NOT NULL) OR approval_status IN ('rejected','rolled_back')),
    CONSTRAINT url_redirects_activation_check CHECK (approval_status NOT IN ('activated','verified') OR activated_at IS NOT NULL),
    CONSTRAINT url_redirects_verified_check CHECK (approval_status<>'verified' OR verified_at IS NOT NULL)
);

ALTER TABLE public.fault_translations
    ADD COLUMN publication_status text NOT NULL DEFAULT 'draft',
    ADD COLUMN source_hash text,
    ADD COLUMN reviewed_at timestamptz,
    ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(),
    ADD CONSTRAINT fault_translations_status_check CHECK(publication_status IN ('draft','review','published','archived')),
    ADD CONSTRAINT fault_translations_published_check CHECK(publication_status<>'published' OR btrim(symptom_name)<>''),
    ADD CONSTRAINT fault_translations_locale_fk FOREIGN KEY(locale) REFERENCES public.locales(code) ON DELETE RESTRICT NOT VALID;
ALTER TABLE public.fault_translations VALIDATE CONSTRAINT fault_translations_locale_fk;

ALTER TABLE public.entity_url_bindings
    ADD COLUMN model_variant_id bigint NULL REFERENCES public.model_variants(id) ON DELETE RESTRICT,
    ADD COLUMN guide_id bigint NULL REFERENCES public.guides(id) ON DELETE RESTRICT;
ALTER TABLE public.url_registry DROP CONSTRAINT url_registry_page_type_check;
ALTER TABLE public.url_registry ADD CONSTRAINT url_registry_page_type_check
    CHECK(page_type IN ('brand','category','model','model_variant','product_code','error_code','fault','article','guide','static','unknown'));
ALTER TABLE public.entity_url_bindings DROP CONSTRAINT entity_url_bindings_one_target_check;
ALTER TABLE public.entity_url_bindings ADD CONSTRAINT entity_url_bindings_one_entity
    CHECK(num_nonnulls(brand_id,category_id,model_id,model_variant_id,product_code_id,error_code_id,fault_id,article_id,guide_id)=1);
ALTER TABLE public.entity_url_bindings DROP CONSTRAINT entity_url_bindings_identity_key;
DROP INDEX public.entity_url_bindings_entity_idx;
DROP INDEX public.entity_url_bindings_one_current_candidate_uidx;
DROP INDEX public.entity_url_bindings_one_current_primary_uidx;
ALTER TABLE public.entity_url_bindings DROP COLUMN entity_key;
ALTER TABLE public.entity_url_bindings ADD COLUMN entity_key text GENERATED ALWAYS AS (
    CASE WHEN brand_id IS NOT NULL THEN 'brand:'||brand_id::text WHEN category_id IS NOT NULL THEN 'category:'||category_id::text
         WHEN model_id IS NOT NULL THEN 'model:'||model_id::text WHEN model_variant_id IS NOT NULL THEN 'model_variant:'||model_variant_id::text
         WHEN product_code_id IS NOT NULL THEN 'product_code:'||product_code_id::text WHEN error_code_id IS NOT NULL THEN 'error_code:'||error_code_id::text
         WHEN fault_id IS NOT NULL THEN 'fault:'||fault_id::text WHEN article_id IS NOT NULL THEN 'article:'||article_id::text
         WHEN guide_id IS NOT NULL THEN 'guide:'||guide_id::text END
) STORED;
ALTER TABLE public.entity_url_bindings ADD CONSTRAINT entity_url_bindings_identity_key UNIQUE(url_id,entity_key,valid_from);
CREATE INDEX entity_url_bindings_entity_idx ON public.entity_url_bindings(entity_key,mapping_status);
CREATE UNIQUE INDEX entity_url_bindings_one_current_primary_v1_uidx ON public.entity_url_bindings(url_id) WHERE valid_to IS NULL AND mapping_status='verified' AND binding_role='primary';
CREATE UNIQUE INDEX entity_url_bindings_one_current_candidate_v1_uidx ON public.entity_url_bindings(url_id,entity_key) WHERE valid_to IS NULL AND mapping_status IN ('candidate','verified');

CREATE OR REPLACE FUNCTION public.validate_model_scope()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE a_brand integer; a_category integer; b_brand integer; b_category integer; variant_model integer;
BEGIN
    IF TG_TABLE_NAME='legacy_model_mapping' THEN
        SELECT brand_id,category_id INTO a_brand,a_category FROM public.models WHERE id=NEW.legacy_model_id;
        SELECT brand_id,category_id INTO b_brand,b_category FROM public.models WHERE id=NEW.canonical_model_id;
    ELSE
        SELECT brand_id,category_id INTO a_brand,a_category FROM public.models WHERE id=NEW.legacy_model_id;
        SELECT brand_id,category_id INTO b_brand,b_category FROM public.models WHERE id=NEW.candidate_model_id;
    END IF;
    IF (a_brand,a_category) IS DISTINCT FROM (b_brand,b_category) THEN RAISE EXCEPTION 'cross-scope model mapping is prohibited'; END IF;
    IF TG_TABLE_NAME='legacy_model_mapping' THEN
        IF NEW.model_variant_id IS NOT NULL THEN
            SELECT model_id INTO variant_model FROM public.model_variants WHERE id=NEW.model_variant_id;
            IF variant_model IS DISTINCT FROM NEW.canonical_model_id THEN RAISE EXCEPTION 'mapped variant must belong to canonical model'; END IF;
        END IF;
    END IF;
    RETURN NEW;
END $$;
CREATE CONSTRAINT TRIGGER legacy_model_mapping_scope AFTER INSERT OR UPDATE ON public.legacy_model_mapping DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.validate_model_scope();
CREATE CONSTRAINT TRIGGER legacy_model_candidates_scope AFTER INSERT OR UPDATE ON public.legacy_model_mapping_candidates DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.validate_model_scope();

CREATE OR REPLACE FUNCTION public.validate_product_code_variant()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE variant_model integer;
BEGIN
    IF NEW.model_variant_id IS NULL THEN RETURN NEW; END IF;
    SELECT model_id INTO variant_model FROM public.model_variants WHERE id=NEW.model_variant_id;
    IF variant_model IS DISTINCT FROM NEW.model_id THEN RAISE EXCEPTION 'product code variant must belong to product code model'; END IF;
    RETURN NEW;
END $$;
CREATE CONSTRAINT TRIGGER product_codes_variant_model AFTER INSERT OR UPDATE OF model_id,model_variant_id ON public.product_codes DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.validate_product_code_variant();

CREATE OR REPLACE FUNCTION public.validate_subject_model_scope()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE m_brand integer; m_category integer; s_brand integer; s_category integer;
BEGIN
    SELECT brand_id,category_id INTO m_brand,m_category FROM public.models WHERE id=NEW.model_id;
    IF TG_TABLE_NAME='error_code_model_overrides' THEN SELECT brand_id,category_id INTO s_brand,s_category FROM public.error_codes WHERE id=NEW.error_code_id;
    ELSE SELECT brand_id,category_id INTO s_brand,s_category FROM public.faults WHERE id=NEW.fault_id; END IF;
    IF (m_brand,m_category) IS DISTINCT FROM (s_brand,s_category) THEN RAISE EXCEPTION 'cross-scope model override is prohibited'; END IF;
    RETURN NEW;
END $$;
CREATE CONSTRAINT TRIGGER error_code_override_scope AFTER INSERT OR UPDATE ON public.error_code_model_overrides DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.validate_subject_model_scope();
CREATE CONSTRAINT TRIGGER fault_override_scope AFTER INSERT OR UPDATE ON public.fault_model_overrides DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.validate_subject_model_scope();

CREATE OR REPLACE FUNCTION public.validate_guide_relation_scope()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE g_brand integer; g_category integer; s_brand integer; s_category integer;
BEGIN
    SELECT brand_id,category_id INTO g_brand,g_category FROM public.guides WHERE id=NEW.guide_id;
    IF TG_TABLE_NAME='guide_models' THEN SELECT brand_id,category_id INTO s_brand,s_category FROM public.models WHERE id=NEW.model_id;
    ELSIF TG_TABLE_NAME='guide_error_codes' THEN SELECT brand_id,category_id INTO s_brand,s_category FROM public.error_codes WHERE id=NEW.error_code_id;
    ELSE SELECT brand_id,category_id INTO s_brand,s_category FROM public.faults WHERE id=NEW.fault_id; END IF;
    IF g_category IS DISTINCT FROM s_category OR (g_brand IS NOT NULL AND g_brand IS DISTINCT FROM s_brand) THEN
        RAISE EXCEPTION 'guide relation crosses guide scope';
    END IF;
    RETURN NEW;
END $$;
CREATE CONSTRAINT TRIGGER guide_models_scope AFTER INSERT OR UPDATE ON public.guide_models DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.validate_guide_relation_scope();
CREATE CONSTRAINT TRIGGER guide_error_codes_scope AFTER INSERT OR UPDATE ON public.guide_error_codes DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.validate_guide_relation_scope();
CREATE CONSTRAINT TRIGGER guide_faults_scope AFTER INSERT OR UPDATE ON public.guide_faults DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.validate_guide_relation_scope();

CREATE OR REPLACE FUNCTION public.validate_article_guide_scope()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE g_brand integer; g_category integer; a_brand integer; a_category integer;
BEGIN
    SELECT brand_id,category_id INTO g_brand,g_category FROM public.guides WHERE id=NEW.guide_id;
    SELECT COALESCE(ec.brand_id,f.brand_id),COALESCE(ec.category_id,f.category_id)
      INTO a_brand,a_category
      FROM public.articles a
      LEFT JOIN public.error_codes ec ON ec.id=a.error_code_id
      LEFT JOIN public.faults f ON f.id=a.fault_id
     WHERE a.id=NEW.article_id;
    IF g_category IS DISTINCT FROM a_category OR (g_brand IS NOT NULL AND g_brand IS DISTINCT FROM a_brand) THEN
        RAISE EXCEPTION 'article guide relation crosses guide scope';
    END IF;
    RETURN NEW;
END $$;
CREATE CONSTRAINT TRIGGER article_guides_scope AFTER INSERT OR UPDATE ON public.article_guides DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.validate_article_guide_scope();

CREATE OR REPLACE FUNCTION public.validate_published_guide_topics()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.content_status='published' AND NOT NEW.is_general AND
       NOT EXISTS(SELECT 1 FROM public.guide_error_codes WHERE guide_id=NEW.id AND relation_status='verified') AND
       NOT EXISTS(SELECT 1 FROM public.guide_faults WHERE guide_id=NEW.id AND relation_status='verified')
    THEN RAISE EXCEPTION 'published guide requires a verified topic or is_general=true'; END IF;
    RETURN NEW;
END $$;
CREATE CONSTRAINT TRIGGER guides_published_topics AFTER INSERT OR UPDATE ON public.guides DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.validate_published_guide_topics();

CREATE OR REPLACE FUNCTION public.revalidate_affected_guide()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE affected_guide_id bigint; guide_row public.guides%ROWTYPE;
BEGIN
    affected_guide_id := CASE WHEN TG_OP='DELETE' THEN OLD.guide_id ELSE NEW.guide_id END;
    SELECT * INTO guide_row FROM public.guides WHERE id=affected_guide_id;
    IF FOUND AND guide_row.content_status='published' AND NOT guide_row.is_general AND
       NOT EXISTS(SELECT 1 FROM public.guide_error_codes WHERE guide_id=affected_guide_id AND relation_status='verified') AND
       NOT EXISTS(SELECT 1 FROM public.guide_faults WHERE guide_id=affected_guide_id AND relation_status='verified')
    THEN RAISE EXCEPTION 'published guide requires a verified topic or is_general=true'; END IF;
    RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END;
END $$;
CREATE CONSTRAINT TRIGGER guide_error_codes_revalidate AFTER INSERT OR UPDATE OR DELETE ON public.guide_error_codes DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.revalidate_affected_guide();
CREATE CONSTRAINT TRIGGER guide_faults_revalidate AFTER INSERT OR UPDATE OR DELETE ON public.guide_faults DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.revalidate_affected_guide();

CREATE OR REPLACE FUNCTION public.prevent_referenced_source_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF EXISTS(SELECT 1 FROM public.source_evidence WHERE source_id=OLD.id) THEN RAISE EXCEPTION 'referenced sources are immutable'; END IF;
    RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END;
END $$;
CREATE TRIGGER sources_immutable_when_referenced BEFORE UPDATE OR DELETE ON public.sources FOR EACH ROW EXECUTE FUNCTION public.prevent_referenced_source_mutation();

CREATE OR REPLACE FUNCTION public.validate_url_redirect_activation()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE src public.url_registry%ROWTYPE; dst public.url_registry%ROWTYPE;
BEGIN
    IF NEW.approval_status NOT IN ('activated','verified') THEN RETURN NEW; END IF;
    SELECT * INTO src FROM public.url_registry WHERE id=NEW.source_url_id;
    SELECT * INTO dst FROM public.url_registry WHERE id=NEW.destination_url_id;
    IF (src.site_id,src.environment) IS DISTINCT FROM (dst.site_id,dst.environment) THEN RAISE EXCEPTION 'redirect crosses site or environment'; END IF;
    IF dst.http_status<>200 OR dst.canonical_url IS DISTINCT FROM dst.normalized_url THEN RAISE EXCEPTION 'redirect destination must be 200 and self-canonical'; END IF;
    IF EXISTS(SELECT 1 FROM public.url_redirects WHERE source_url_id=NEW.destination_url_id AND id<>NEW.id AND approval_status IN ('activated','verified')) THEN RAISE EXCEPTION 'redirect chain is prohibited'; END IF;
    IF NOT EXISTS(SELECT 1 FROM public.entity_url_bindings s JOIN public.entity_url_bindings d ON d.entity_key=s.entity_key WHERE s.url_id=NEW.source_url_id AND d.url_id=NEW.destination_url_id AND s.mapping_status='verified' AND d.mapping_status='verified' AND s.valid_to IS NULL AND d.valid_to IS NULL) THEN RAISE EXCEPTION 'redirect requires exact verified semantic binding'; END IF;
    RETURN NEW;
END $$;
CREATE CONSTRAINT TRIGGER url_redirect_activation AFTER INSERT OR UPDATE ON public.url_redirects DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.validate_url_redirect_activation();

DO $triggers$
DECLARE table_name text;
BEGIN
    FOREACH table_name IN ARRAY ARRAY['model_variants','legacy_model_mapping','legacy_model_mapping_candidates','model_content_translations','error_code_translations','guides','guide_translations','article_guides','guide_error_codes','guide_faults','guide_models','error_code_model_overrides','fault_model_overrides','url_redirects','fault_translations','entity_url_bindings','url_registry'] LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS information_model_updated_at ON public.%I',table_name);
        EXECUTE format('CREATE TRIGGER information_model_updated_at BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.set_information_model_updated_at()',table_name);
    END LOOP;
END $triggers$;

DO $security$
DECLARE table_name text;
BEGIN
    FOREACH table_name IN ARRAY ARRAY['model_variants','legacy_model_mapping','legacy_model_mapping_candidates','model_content_translations','error_code_translations','guides','guide_translations','sources','source_evidence','article_guides','guide_error_codes','guide_faults','guide_models','error_code_model_overrides','fault_model_overrides','url_redirects'] LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',table_name);
        EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY',table_name);
        EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC, anon, authenticated',table_name);
        EXECUTE format('GRANT SELECT,INSERT,UPDATE ON public.%I TO service_role',table_name);
    END LOOP;
END $security$;
REVOKE DELETE ON public.model_variants,public.legacy_model_mapping,public.legacy_model_mapping_candidates,public.model_content_translations,public.error_code_translations,public.guides,public.guide_translations,public.sources,public.source_evidence,public.article_guides,public.guide_error_codes,public.guide_faults,public.guide_models,public.error_code_model_overrides,public.fault_model_overrides,public.url_redirects FROM service_role;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

CREATE VIEW public.verified_model_variants WITH (security_barrier=true) AS SELECT * FROM public.model_variants WHERE status='verified';
CREATE VIEW public.published_model_content_translations WITH (security_barrier=true) AS SELECT * FROM public.model_content_translations WHERE publication_status='published';
CREATE VIEW public.published_error_code_translations WITH (security_barrier=true) AS SELECT * FROM public.error_code_translations WHERE publication_status='published';
CREATE VIEW public.published_guide_translations WITH (security_barrier=true) AS SELECT * FROM public.guide_translations WHERE publication_status='published';
CREATE VIEW public.verified_article_guides WITH (security_barrier=true) AS SELECT * FROM public.article_guides WHERE relation_status='verified';
CREATE VIEW public.verified_guide_error_codes WITH (security_barrier=true) AS SELECT * FROM public.guide_error_codes WHERE relation_status='verified';
CREATE VIEW public.verified_guide_faults WITH (security_barrier=true) AS SELECT * FROM public.guide_faults WHERE relation_status='verified';
CREATE VIEW public.verified_guide_models WITH (security_barrier=true) AS SELECT * FROM public.guide_models WHERE relation_status='verified';
REVOKE ALL ON public.verified_model_variants,public.published_model_content_translations,public.published_error_code_translations,public.published_guide_translations,public.verified_article_guides,public.verified_guide_error_codes,public.verified_guide_faults,public.verified_guide_models FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.verified_model_variants,public.published_model_content_translations,public.published_error_code_translations,public.published_guide_translations,public.verified_article_guides,public.verified_guide_error_codes,public.verified_guide_faults,public.verified_guide_models TO service_role;

INSERT INTO public.schema_migrations(version,filename) VALUES('016','016_information_model_v1_foundation.sql') ON CONFLICT(version) DO NOTHING;
NOTIFY pgrst,'reload schema';
COMMIT;
