-- Migration 018: local-first idempotent worker execution and audit foundation.
BEGIN;

CREATE TABLE public.worker_batches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id text NOT NULL DEFAULT 'appliance-repair-base',
    job_type text NOT NULL CHECK(btrim(job_type)<>''),
    idempotency_key text NOT NULL CHECK(btrim(idempotency_key)<>''),
    scope_json jsonb NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(scope_json)='object'),
    dry_run boolean NOT NULL DEFAULT true,
    status text NOT NULL DEFAULT 'planned' CHECK(status IN ('planned','running','completed','failed','rolled_back')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    CONSTRAINT worker_batches_identity_key UNIQUE(site_id,job_type,idempotency_key),
    CONSTRAINT worker_batches_completed_check CHECK((status IN ('completed','rolled_back'))=(completed_at IS NOT NULL))
);
CREATE INDEX worker_batches_status_idx ON public.worker_batches(site_id,status,created_at);

CREATE TABLE public.worker_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id bigint NOT NULL REFERENCES public.worker_batches(id) ON DELETE RESTRICT,
    job_key text NOT NULL CHECK(btrim(job_key)<>''),
    payload_json jsonb NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(payload_json)='object'),
    status text NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','running','retry','completed','dead_letter','cancelled')),
    attempts integer NOT NULL DEFAULT 0 CHECK(attempts>=0),
    max_attempts integer NOT NULL DEFAULT 3 CHECK(max_attempts>0),
    available_at timestamptz NOT NULL DEFAULT now(),
    leased_at timestamptz,
    lease_owner text,
    last_error text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    CONSTRAINT worker_jobs_batch_key UNIQUE(batch_id,job_key),
    CONSTRAINT worker_jobs_lease_check CHECK((status='running')=(leased_at IS NOT NULL AND NULLIF(btrim(lease_owner),'') IS NOT NULL)),
    CONSTRAINT worker_jobs_completed_check CHECK((status='completed')=(completed_at IS NOT NULL))
);
CREATE INDEX worker_jobs_claim_idx ON public.worker_jobs(status,available_at,id);
CREATE INDEX worker_jobs_batch_status_idx ON public.worker_jobs(batch_id,status);

CREATE TABLE public.worker_observations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id bigint NOT NULL REFERENCES public.worker_jobs(id) ON DELETE RESTRICT,
    observation_key text NOT NULL CHECK(btrim(observation_key)<>''),
    entity_type text NOT NULL CHECK(entity_type IN ('model','model_variant','product_code','error_code','fault','guide','source','url')),
    normalized_key text NOT NULL CHECK(btrim(normalized_key)<>''),
    observed_data jsonb NOT NULL CHECK(jsonb_typeof(observed_data)='object'),
    candidate_status text NOT NULL DEFAULT 'candidate' CHECK(candidate_status IN ('candidate','verified','rejected','conflicted')),
    source_evidence_id bigint REFERENCES public.source_evidence(id) ON DELETE SET NULL,
    observed_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT worker_observations_job_key UNIQUE(job_id,observation_key)
);
CREATE INDEX worker_observations_entity_idx ON public.worker_observations(entity_type,normalized_key,candidate_status);

CREATE TABLE public.worker_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id bigint NOT NULL REFERENCES public.worker_batches(id) ON DELETE RESTRICT,
    job_id bigint REFERENCES public.worker_jobs(id) ON DELETE RESTRICT,
    event_type text NOT NULL CHECK(event_type IN ('batch_created','job_queued','job_claimed','job_completed','job_retry','job_dead_letter','batch_completed','batch_failed','batch_rolled_back')),
    details_json jsonb NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(details_json)='object'),
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX worker_events_batch_time_idx ON public.worker_events(batch_id,created_at,id);

DO $triggers$
DECLARE table_name text;
BEGIN
    FOREACH table_name IN ARRAY ARRAY['worker_batches','worker_jobs'] LOOP
        EXECUTE format('CREATE TRIGGER information_model_updated_at BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.set_information_model_updated_at()',table_name);
    END LOOP;
END $triggers$;

DO $security$
DECLARE table_name text;
BEGIN
    FOREACH table_name IN ARRAY ARRAY['worker_batches','worker_jobs','worker_observations','worker_events'] LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',table_name);
        EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY',table_name);
        EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC,anon,authenticated',table_name);
        EXECUTE format('GRANT SELECT,INSERT,UPDATE ON public.%I TO service_role',table_name);
        EXECUTE format('REVOKE DELETE ON public.%I FROM service_role',table_name);
    END LOOP;
END $security$;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

INSERT INTO public.schema_migrations(version,filename)
VALUES('018','018_worker_platform.sql') ON CONFLICT(version) DO NOTHING;
COMMIT;
