-- Migration 019: site contracts and isolated publication/presentation scope.
BEGIN;

CREATE TABLE public.sites (
    id text PRIMARY KEY CHECK(id ~ '^[a-z][a-z0-9-]*$'),
    name text NOT NULL CHECK(btrim(name)<>''),
    domain text NOT NULL UNIQUE CHECK(domain ~ '^[a-z0-9.-]+$'),
    vertical_key text NOT NULL CHECK(btrim(vertical_key)<>''),
    default_locale text NOT NULL REFERENCES public.locales(code) ON DELETE RESTRICT,
    status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','active','archived')),
    contract_json jsonb NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(contract_json)='object'),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.sites(id,name,domain,vertical_key,default_locale,status,contract_json)
VALUES('appliance-repair-base','Appliance Repair Base','appliancerepairbase.com','appliance-repair','en','active',
       '{"url_policy":"preserve","knowledge_scope":"shared","publication_scope":"site"}'::jsonb);

CREATE TABLE public.site_locales (
    site_id text NOT NULL REFERENCES public.sites(id) ON DELETE RESTRICT,
    locale text NOT NULL REFERENCES public.locales(code) ON DELETE RESTRICT,
    is_default boolean NOT NULL DEFAULT false,
    status text NOT NULL DEFAULT 'active' CHECK(status IN ('active','disabled')),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY(site_id,locale)
);
INSERT INTO public.site_locales(site_id,locale,is_default)
SELECT 'appliance-repair-base',code,is_default FROM public.locales WHERE is_active;
CREATE UNIQUE INDEX site_locales_one_default_uidx ON public.site_locales(site_id) WHERE is_default AND status='active';

ALTER TABLE public.url_registry DROP CONSTRAINT url_registry_site_check;
ALTER TABLE public.url_registry ADD CONSTRAINT url_registry_site_fk
    FOREIGN KEY(site_id) REFERENCES public.sites(id) ON DELETE RESTRICT;
ALTER TABLE public.worker_batches ADD CONSTRAINT worker_batches_site_fk
    FOREIGN KEY(site_id) REFERENCES public.sites(id) ON DELETE RESTRICT;

CREATE TABLE public.site_entity_publications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id text NOT NULL REFERENCES public.sites(id) ON DELETE RESTRICT,
    locale text NOT NULL REFERENCES public.locales(code) ON DELETE RESTRICT,
    model_id integer REFERENCES public.models(id) ON DELETE RESTRICT,
    model_variant_id bigint REFERENCES public.model_variants(id) ON DELETE RESTRICT,
    error_code_id integer REFERENCES public.error_codes(id) ON DELETE RESTRICT,
    fault_id integer REFERENCES public.faults(id) ON DELETE RESTRICT,
    article_id integer REFERENCES public.articles(id) ON DELETE RESTRICT,
    guide_id bigint REFERENCES public.guides(id) ON DELETE RESTRICT,
    publication_status text NOT NULL DEFAULT 'draft' CHECK(publication_status IN ('draft','review','published','archived')),
    canonical_url_id bigint REFERENCES public.url_registry(id) ON DELETE RESTRICT,
    indexable boolean NOT NULL DEFAULT false,
    published_at timestamptz,
    reviewed_at timestamptz,
    reviewed_by text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    entity_key text GENERATED ALWAYS AS(
        CASE WHEN model_id IS NOT NULL THEN 'model:'||model_id::text
             WHEN model_variant_id IS NOT NULL THEN 'model_variant:'||model_variant_id::text
             WHEN error_code_id IS NOT NULL THEN 'error_code:'||error_code_id::text
             WHEN fault_id IS NOT NULL THEN 'fault:'||fault_id::text
             WHEN article_id IS NOT NULL THEN 'article:'||article_id::text
             WHEN guide_id IS NOT NULL THEN 'guide:'||guide_id::text END
    ) STORED,
    CONSTRAINT site_publications_one_entity CHECK(num_nonnulls(model_id,model_variant_id,error_code_id,fault_id,article_id,guide_id)=1),
    CONSTRAINT site_publications_publish_check CHECK(
        (publication_status='published' AND published_at IS NOT NULL AND reviewed_at IS NOT NULL AND NULLIF(btrim(reviewed_by),'') IS NOT NULL)
        OR (publication_status<>'published' AND published_at IS NULL)
    ),
    CONSTRAINT site_publications_indexable_url_check CHECK(NOT indexable OR (publication_status='published' AND canonical_url_id IS NOT NULL)),
    CONSTRAINT site_publications_identity_key UNIQUE(site_id,locale,entity_key)
);
CREATE INDEX site_publications_status_idx ON public.site_entity_publications(site_id,locale,publication_status,entity_key);
CREATE INDEX site_publications_url_idx ON public.site_entity_publications(canonical_url_id);

CREATE OR REPLACE FUNCTION public.validate_site_publication()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE configured boolean; url_site text; url_env text; url_status smallint; url_canonical text; normalized text;
BEGIN
    SELECT EXISTS(SELECT 1 FROM public.site_locales WHERE site_id=NEW.site_id AND locale=NEW.locale AND status='active') INTO configured;
    IF NOT configured THEN RAISE EXCEPTION 'publication locale is not active for site'; END IF;
    IF NEW.canonical_url_id IS NOT NULL THEN
        SELECT site_id,environment,http_status,canonical_url,normalized_url INTO url_site,url_env,url_status,url_canonical,normalized
        FROM public.url_registry WHERE id=NEW.canonical_url_id;
        IF url_site IS DISTINCT FROM NEW.site_id THEN RAISE EXCEPTION 'publication canonical URL belongs to another site'; END IF;
        IF NEW.publication_status='published' AND NEW.indexable AND (url_status<>200 OR url_canonical IS DISTINCT FROM normalized) THEN
            RAISE EXCEPTION 'indexable publication requires canonical 200 self-canonical URL';
        END IF;
    END IF;
    RETURN NEW;
END $$;
CREATE CONSTRAINT TRIGGER site_publication_validate AFTER INSERT OR UPDATE ON public.site_entity_publications
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.validate_site_publication();

CREATE TRIGGER information_model_updated_at BEFORE UPDATE ON public.sites
    FOR EACH ROW EXECUTE FUNCTION public.set_information_model_updated_at();
CREATE TRIGGER information_model_updated_at BEFORE UPDATE ON public.site_entity_publications
    FOR EACH ROW EXECUTE FUNCTION public.set_information_model_updated_at();

DO $security$
DECLARE table_name text;
BEGIN
    FOREACH table_name IN ARRAY ARRAY['sites','site_locales','site_entity_publications'] LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',table_name);
        EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY',table_name);
        EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC,anon,authenticated',table_name);
        EXECUTE format('GRANT SELECT,INSERT,UPDATE ON public.%I TO service_role',table_name);
        EXECUTE format('REVOKE DELETE ON public.%I FROM service_role',table_name);
    END LOOP;
END $security$;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

CREATE POLICY "api public owner active sites" ON public.sites FOR SELECT TO api_public_owner USING(status='active');
CREATE POLICY "api public owner active site locales" ON public.site_locales FOR SELECT TO api_public_owner USING(status='active');
CREATE POLICY "api public owner published site entities" ON public.site_entity_publications FOR SELECT TO api_public_owner USING(publication_status='published');
CREATE POLICY "api public owner canonical site urls" ON public.url_registry FOR SELECT TO api_public_owner
    USING(http_status=200 AND canonical_url=normalized_url);
GRANT SELECT(id,name,domain,vertical_key,default_locale,status) ON public.sites TO api_public_owner;
GRANT SELECT(site_id,locale,is_default,status) ON public.site_locales TO api_public_owner;
GRANT SELECT(site_id,locale,model_id,guide_id,publication_status,canonical_url_id,indexable,entity_key)
    ON public.site_entity_publications TO api_public_owner;
GRANT SELECT(id,site_id,normalized_url,path,http_status,canonical_url) ON public.url_registry TO api_public_owner;

CREATE VIEW api_public.sites_v1 WITH(security_barrier=true) AS
SELECT id AS site_id,name,domain,vertical_key,default_locale
FROM public.sites WHERE status='active';
ALTER VIEW api_public.sites_v1 OWNER TO api_public_owner;

CREATE VIEW api_public.site_models_v1 WITH(security_barrier=true) AS
SELECT p.site_id,p.locale,m.model_id,m.brand_key,m.category_key,m.product_line_key,
       m.name,m.slug,m.series,m.release_year,m.manual_url,m.updated_at,
       u.path AS canonical_path,p.indexable
FROM public.site_entity_publications p
JOIN public.api_public_identities i ON i.resource_type='model' AND i.source_id=p.model_id
JOIN api_public.models m ON m.model_id=i.public_id
LEFT JOIN public.url_registry u ON u.id=p.canonical_url_id
WHERE p.publication_status='published';
ALTER VIEW api_public.site_models_v1 OWNER TO api_public_owner;

CREATE VIEW api_public.site_guides_v1 WITH(security_barrier=true) AS
SELECT p.site_id,p.locale,g.guide_id,g.category_key,g.brand_key,g.slug,g.title,
       g.short_description,g.summary,g.steps_json,g.default_difficulty,
       g.default_estimated_minutes,g.safety_notes,g.is_general,
       u.path AS canonical_path,p.indexable
FROM public.site_entity_publications p
JOIN api_public.guides_v1 g
  ON g.guide_id=uuid_generate_v5(uuid_ns_url(),'repairbase:v1:guide:'||p.guide_id::text)
 AND g.locale=p.locale
LEFT JOIN public.url_registry u ON u.id=p.canonical_url_id
WHERE p.publication_status='published';
ALTER VIEW api_public.site_guides_v1 OWNER TO api_public_owner;

CREATE VIEW api_public.site_sitemap_entries_v1 WITH(security_barrier=true) AS
SELECT p.site_id,p.locale,p.entity_key,u.normalized_url,u.path AS canonical_path
FROM public.site_entity_publications p
JOIN public.url_registry u ON u.id=p.canonical_url_id
WHERE p.publication_status='published' AND p.indexable
  AND u.http_status=200 AND u.canonical_url=u.normalized_url;
ALTER VIEW api_public.site_sitemap_entries_v1 OWNER TO api_public_owner;

REVOKE ALL ON api_public.sites_v1,api_public.site_models_v1,api_public.site_guides_v1,
    api_public.site_sitemap_entries_v1 FROM PUBLIC;
GRANT SELECT ON api_public.sites_v1,api_public.site_models_v1,api_public.site_guides_v1,
    api_public.site_sitemap_entries_v1 TO anon,authenticated;

INSERT INTO public.schema_migrations(version,filename)
VALUES('019','019_multisite_publication_foundation.sql') ON CONFLICT(version) DO NOTHING;
NOTIFY pgrst,'reload schema';
COMMIT;
