-- Worker 1: persistent cube scope, observations, findings and backlog.
BEGIN;

CREATE TABLE public.worker_runs (
 id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), worker_name text NOT NULL, worker_version text NOT NULL,
 site_id text NOT NULL REFERENCES public.sites(id) ON DELETE RESTRICT,
 environment text NOT NULL CHECK(environment IN('development','staging','production')),
 scope_snapshot_id bigint, dry_run boolean NOT NULL, status text NOT NULL CHECK(status IN('running','completed','failed')),
 result_json jsonb NOT NULL DEFAULT '{}'::jsonb, started_at timestamptz NOT NULL DEFAULT now(), finished_at timestamptz
);
CREATE TABLE public.cube_scope_snapshots (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, scope_version integer NOT NULL,
 site_id text NOT NULL REFERENCES public.sites(id) ON DELETE RESTRICT,
 environment text NOT NULL CHECK(environment IN('development','staging','production')),
 brands_json jsonb NOT NULL CHECK(jsonb_typeof(brands_json)='array'), categories_json jsonb NOT NULL CHECK(jsonb_typeof(categories_json)='array'),
 locales_json jsonb NOT NULL CHECK(jsonb_typeof(locales_json)='array'), status text NOT NULL CHECK(status IN('active','superseded')),
 created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(site_id,environment,scope_version)
);
CREATE UNIQUE INDEX cube_scope_one_active_uidx ON public.cube_scope_snapshots(site_id,environment) WHERE status='active';
ALTER TABLE public.worker_runs ADD CONSTRAINT worker_runs_scope_fk FOREIGN KEY(scope_snapshot_id) REFERENCES public.cube_scope_snapshots(id) ON DELETE RESTRICT;

CREATE TABLE public.cube_coverage_observations (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, run_id uuid NOT NULL REFERENCES public.worker_runs(id) ON DELETE RESTRICT,
 scope_snapshot_id bigint NOT NULL REFERENCES public.cube_scope_snapshots(id) ON DELETE RESTRICT,
 site_id text NOT NULL, environment text NOT NULL, brand_id integer, category_id integer, locale text,
 metric_name text NOT NULL, numerator integer, denominator integer, percentage numeric(7,3),
 availability text NOT NULL CHECK(availability IN('available','not_available','not_applicable','unknown')),
 definition text NOT NULL, observed_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(run_id,brand_id,category_id,locale,metric_name)
);

CREATE TABLE public.findings (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, site_id text NOT NULL, environment text NOT NULL,
 scope_snapshot_id bigint NOT NULL REFERENCES public.cube_scope_snapshots(id) ON DELETE RESTRICT,
 entity_type text NOT NULL, entity_id text NOT NULL, locale text, finding_type text NOT NULL,
 severity text NOT NULL CHECK(severity IN('critical','high','medium','low')),
 status text NOT NULL DEFAULT 'open' CHECK(status IN('open','acknowledged','resolved','ignored','false_positive')),
 details_json jsonb NOT NULL DEFAULT '{}'::jsonb, detector_name text NOT NULL, detector_version text NOT NULL,
 finding_hash text NOT NULL UNIQUE, first_seen_at timestamptz NOT NULL DEFAULT now(), last_seen_at timestamptz NOT NULL DEFAULT now(),
 resolved_at timestamptz, source_run_id uuid NOT NULL REFERENCES public.worker_runs(id) ON DELETE RESTRICT,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX findings_open_scope_idx ON public.findings(site_id,environment,scope_snapshot_id,status,finding_type);

CREATE TABLE public.content_backlog (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, site_id text NOT NULL, environment text NOT NULL,
 scope_snapshot_id bigint NOT NULL REFERENCES public.cube_scope_snapshots(id) ON DELETE RESTRICT,
 finding_id bigint NOT NULL REFERENCES public.findings(id) ON DELETE RESTRICT,
 entity_type text NOT NULL, entity_id text NOT NULL, locale text, action_type text NOT NULL,
 priority integer NOT NULL CHECK(priority BETWEEN 0 AND 100), priority_band text NOT NULL CHECK(priority_band IN('P0','P1','P2','P3')),
 risk_level text NOT NULL CHECK(risk_level IN('low','medium','high','safety_review')),
 status text NOT NULL CHECK(status IN('queued','blocked','in_progress','completed','cancelled','deferred')),
 reason_json jsonb NOT NULL, dependency_json jsonb NOT NULL DEFAULT '{}'::jsonb,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz
);
CREATE UNIQUE INDEX content_backlog_one_active_uidx ON public.content_backlog(finding_id,action_type)
 WHERE status IN('queued','blocked','in_progress','deferred');

DO $security$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['worker_runs','cube_scope_snapshots','cube_coverage_observations','findings','content_backlog'] LOOP
  EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t);
  EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY',t);
  EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC,anon,authenticated',t);
  EXECUTE format('GRANT SELECT,INSERT,UPDATE ON public.%I TO service_role',t);
  EXECUTE format('REVOKE DELETE ON public.%I FROM service_role',t);
 END LOOP;
END $security$;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
INSERT INTO public.schema_migrations(version,filename) VALUES('020','020_cube_coverage_backlog_worker.sql') ON CONFLICT(version) DO NOTHING;
COMMIT;
