-- PR 2A: source discovery candidates only; no facts or content mutations.
BEGIN;
CREATE TABLE public.source_candidates (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 site_id text NOT NULL REFERENCES public.sites(id) ON DELETE RESTRICT,
 environment text NOT NULL CHECK(environment IN('development','staging','production')),
 backlog_id bigint NOT NULL REFERENCES public.content_backlog(id) ON DELETE RESTRICT,
 entity_type text NOT NULL, entity_id text NOT NULL, locale text,
 source_type text NOT NULL CHECK(source_type IN('manufacturer','official_parts','service_manual','retailer','forum','other')),
 candidate_url text, normalized_url text, publisher text, title text,
 confidence smallint NOT NULL CHECK(confidence BETWEEN 0 AND 100),
 status text NOT NULL CHECK(status IN('candidate','accepted','rejected','not_found')),
 discovery_method text NOT NULL, details_json jsonb NOT NULL DEFAULT '{}'::jsonb,
 first_seen_at timestamptz NOT NULL DEFAULT now(), last_seen_at timestamptz NOT NULL DEFAULT now(),
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 candidate_key text GENERATED ALWAYS AS(COALESCE(normalized_url,'__not_found__')) STORED,
 UNIQUE(site_id,environment,backlog_id,candidate_key),
 CONSTRAINT source_candidate_not_found_check CHECK(status<>'not_found' OR (candidate_url IS NULL AND normalized_url IS NULL))
);
CREATE INDEX source_candidates_backlog_status_idx ON public.source_candidates(site_id,environment,backlog_id,status);

CREATE TABLE public.source_discovery_cache (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 provider text NOT NULL, query_hash text NOT NULL, query_text text NOT NULL,
 response_json jsonb NOT NULL CHECK(jsonb_typeof(response_json)='array'),
 fetched_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL,
 UNIQUE(provider,query_hash)
);
DO $security$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['source_candidates','source_discovery_cache'] LOOP
  EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t);
  EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY',t);
  EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC,anon,authenticated',t);
  EXECUTE format('GRANT SELECT,INSERT,UPDATE ON public.%I TO service_role',t);
  EXECUTE format('REVOKE DELETE ON public.%I FROM service_role',t);
 END LOOP;
END $security$;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
INSERT INTO public.schema_migrations(version,filename) VALUES('021','021_source_discovery_worker.sql') ON CONFLICT(version) DO NOTHING;
COMMIT;
