-- PR 2B: immutable fetch/document versions and unverified candidate facts.
BEGIN;

CREATE TABLE public.source_fetches (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 source_id bigint REFERENCES public.sources(id) ON DELETE RESTRICT,
 source_candidate_id bigint NOT NULL REFERENCES public.source_candidates(id) ON DELETE RESTRICT,
 backlog_id bigint NOT NULL REFERENCES public.content_backlog(id) ON DELETE RESTRICT,
 worker_run_id uuid REFERENCES public.worker_runs(id) ON DELETE SET NULL,
 requested_url text NOT NULL, final_url text,
 http_status integer CHECK(http_status BETWEEN 100 AND 599), mime_type text,
 content_length bigint CHECK(content_length IS NULL OR content_length>=0), etag text, last_modified text,
 retrieved_at timestamptz NOT NULL DEFAULT now(),
 fetch_status text NOT NULL CHECK(fetch_status IN('pending','fetched','not_modified','unsupported','blocked','failed','too_large','invalid_content')),
 processing_state text NOT NULL DEFAULT 'fetch_pending' CHECK(processing_state IN('fetch_pending','source_material_fetched','candidate_facts_available','needs_entity_resolution','needs_manual_review')),
 failure_reason text, content_hash text, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
 created_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT source_fetch_content_status_check CHECK(fetch_status<>'fetched' OR content_hash IS NOT NULL)
);
CREATE INDEX source_fetches_candidate_idx ON public.source_fetches(source_candidate_id,retrieved_at DESC);
CREATE UNIQUE INDEX source_fetches_version_uidx ON public.source_fetches(source_candidate_id,content_hash)
 WHERE fetch_status='fetched' AND content_hash IS NOT NULL;

CREATE TABLE public.source_documents (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 source_fetch_id bigint NOT NULL REFERENCES public.source_fetches(id) ON DELETE RESTRICT,
 document_type text NOT NULL CHECK(document_type IN('manufacturer_product_page','manufacturer_support_page','user_manual','service_manual','technical_datasheet','parts_catalog','retailer_product_page','parts_supplier_page','forum_page','unknown')),
 language text, raw_storage_reference text NOT NULL,
 normalized_text text NOT NULL, normalized_text_hash text NOT NULL,
 page_count integer CHECK(page_count IS NULL OR page_count>0),
 parser_name text NOT NULL, parser_version text NOT NULL,
 parse_status text NOT NULL CHECK(parse_status IN('parsed','partial','failed','unsupported')),
 parse_error text, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
 created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(source_fetch_id,parser_name,parser_version)
);

CREATE TABLE public.candidate_facts (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 source_document_id bigint NOT NULL REFERENCES public.source_documents(id) ON DELETE RESTRICT,
 source_candidate_id bigint NOT NULL REFERENCES public.source_candidates(id) ON DELETE RESTRICT,
 backlog_item_id bigint NOT NULL REFERENCES public.content_backlog(id) ON DELETE RESTRICT,
 fact_type text NOT NULL, subject_hint text, predicate text NOT NULL,
 value_json jsonb NOT NULL, unit text, locale text,
 confidence smallint NOT NULL CHECK(confidence BETWEEN 0 AND 100),
 extraction_status text NOT NULL CHECK(extraction_status IN('candidate','needs_review','rejected','conflicted')),
 extractor_name text NOT NULL, extractor_version text NOT NULL, input_hash text NOT NULL,
 conflict_key text, conflict_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(source_document_id,extractor_name,extractor_version,input_hash)
);
CREATE INDEX candidate_facts_resolution_idx ON public.candidate_facts(extraction_status,fact_type,predicate);
CREATE INDEX candidate_facts_conflict_idx ON public.candidate_facts(conflict_key) WHERE conflict_key IS NOT NULL;

CREATE TABLE public.candidate_fact_evidence (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 candidate_fact_id bigint NOT NULL REFERENCES public.candidate_facts(id) ON DELETE RESTRICT,
 source_document_id bigint NOT NULL REFERENCES public.source_documents(id) ON DELETE RESTRICT,
 source_locator text, quoted_excerpt text CHECK(length(quoted_excerpt)<=500),
 page_number integer CHECK(page_number IS NULL OR page_number>0), section_heading text, json_path text,
 character_start integer, character_end integer, created_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT candidate_fact_evidence_locator_check CHECK(
   NULLIF(btrim(source_locator),'') IS NOT NULL OR page_number IS NOT NULL OR
   NULLIF(btrim(json_path),'') IS NOT NULL OR
   (character_start IS NOT NULL AND character_end IS NOT NULL AND character_end>=character_start)
 )
);

DO $security$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['source_fetches','source_documents','candidate_facts','candidate_fact_evidence'] LOOP
  EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t);
  EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY',t);
  EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC,anon,authenticated',t);
  EXECUTE format('GRANT SELECT,INSERT,UPDATE ON public.%I TO service_role',t);
  EXECUTE format('REVOKE DELETE ON public.%I FROM service_role',t);
 END LOOP;
END $security$;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
INSERT INTO public.schema_migrations(version,filename) VALUES('022','022_source_ingestion_enrichment_worker.sql') ON CONFLICT(version) DO NOTHING;
COMMIT;
