-- PR 2C: reviewable proposals only. No canonical/domain writes.
BEGIN;

ALTER TABLE public.candidate_facts ADD COLUMN integration_state text NOT NULL DEFAULT 'unprocessed'
 CHECK(integration_state IN('unprocessed','integration_proposal_created','needs_review','blocked_by_conflict','no_matching_entity','same_as_existing','out_of_scope'));

CREATE TABLE public.integration_proposals (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 site_id text NOT NULL REFERENCES public.sites(id) ON DELETE RESTRICT,
 environment text NOT NULL CHECK(environment IN('development','staging','production')),
 worker_run_id uuid REFERENCES public.worker_runs(id) ON DELETE SET NULL,
 backlog_item_id bigint NOT NULL REFERENCES public.content_backlog(id) ON DELETE RESTRICT,
 candidate_fact_id bigint NOT NULL REFERENCES public.candidate_facts(id) ON DELETE RESTRICT,
 proposal_type text NOT NULL CHECK(proposal_type IN(
  'match_existing_model','match_existing_variant','match_existing_product_code','propose_variant_mapping','propose_product_code_mapping','propose_model_overview_update','propose_model_spec_update',
  'match_existing_error_code','propose_error_code_description','propose_error_code_translation','propose_error_code_product_code_relation','propose_error_code_model_override',
  'match_existing_fault','propose_fault_translation','propose_fault_error_code_relation','propose_fault_model_override',
  'match_existing_guide','propose_new_guide_candidate','propose_guide_translation','propose_guide_error_code_relation','propose_guide_fault_relation','propose_guide_model_relation','propose_article_guide_relation','propose_source_evidence')),
 entity_type text NOT NULL, entity_id text, locale text,
 status text NOT NULL CHECK(status IN('proposed','needs_review','approved','rejected','superseded','blocked','applied','failed')),
 confidence smallint NOT NULL CHECK(confidence BETWEEN 0 AND 100),
 risk_level text NOT NULL CHECK(risk_level IN('low','medium','high','safety_review')),
 difference_class text NOT NULL CHECK(difference_class IN('new_information','same_as_existing','more_specific','conflicts_with_existing','fills_missing_value','translation_gap','relation_gap','out_of_scope','insufficient_evidence')),
 reason_json jsonb NOT NULL, current_value_json jsonb, proposed_value_json jsonb NOT NULL,
 expected_apply_operation text NOT NULL, input_hash text NOT NULL UNIQUE,
 detector_name text NOT NULL, detector_version text NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 reviewed_at timestamptz, reviewed_by text
);
CREATE INDEX integration_proposals_review_idx ON public.integration_proposals(site_id,environment,status,risk_level);
CREATE INDEX integration_proposals_fact_idx ON public.integration_proposals(candidate_fact_id,created_at DESC);

CREATE TABLE public.integration_proposal_targets (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 proposal_id bigint NOT NULL REFERENCES public.integration_proposals(id) ON DELETE RESTRICT,
 target_entity_type text NOT NULL, target_entity_id text,
 match_type text NOT NULL CHECK(match_type IN('exact','normalized_exact','alias','product_code','variant_code','contextual','candidate','conflict','none')),
 match_score smallint NOT NULL CHECK(match_score BETWEEN 0 AND 100), is_preferred boolean NOT NULL DEFAULT false,
 reason_json jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE NULLS NOT DISTINCT(proposal_id,target_entity_type,target_entity_id,match_type)
);
CREATE UNIQUE INDEX integration_proposal_one_preferred_uidx ON public.integration_proposal_targets(proposal_id) WHERE is_preferred;

CREATE TABLE public.integration_proposal_evidence (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 proposal_id bigint NOT NULL REFERENCES public.integration_proposals(id) ON DELETE RESTRICT,
 candidate_fact_id bigint NOT NULL REFERENCES public.candidate_facts(id) ON DELETE RESTRICT,
 candidate_fact_evidence_id bigint REFERENCES public.candidate_fact_evidence(id) ON DELETE RESTRICT,
 source_document_id bigint NOT NULL REFERENCES public.source_documents(id) ON DELETE RESTRICT,
 support_type text NOT NULL CHECK(support_type IN('supports','contradicts','context','identifier_match','scope_match')),
 created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE NULLS NOT DISTINCT(proposal_id,candidate_fact_id,candidate_fact_evidence_id,support_type)
);

CREATE TABLE public.integration_proposal_conflicts (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 proposal_id bigint NOT NULL REFERENCES public.integration_proposals(id) ON DELETE RESTRICT,
 conflict_type text NOT NULL, conflicting_entity_type text, conflicting_entity_id text,
 conflicting_value_json jsonb, severity text NOT NULL CHECK(severity IN('low','medium','high','safety_review')),
 details_json jsonb NOT NULL, status text NOT NULL DEFAULT 'open' CHECK(status IN('open','resolved','dismissed')),
 created_at timestamptz NOT NULL DEFAULT now(), resolved_at timestamptz
);

DO $security$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['integration_proposals','integration_proposal_targets','integration_proposal_evidence','integration_proposal_conflicts'] LOOP
  EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t);
  EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY',t);
  EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC,anon,authenticated',t);
  EXECUTE format('GRANT SELECT,INSERT,UPDATE ON public.%I TO service_role',t);
  EXECUTE format('REVOKE DELETE ON public.%I FROM service_role',t);
 END LOOP;
END $security$;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
INSERT INTO public.schema_migrations(version,filename) VALUES('023','023_knowledge_integration_worker.sql') ON CONFLICT(version) DO NOTHING;
COMMIT;
