-- PR 2D: transactional application audit. Domain mutations remain allowlisted in code.
BEGIN;

CREATE TABLE public.integration_apply_attempts (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 proposal_id bigint NOT NULL REFERENCES public.integration_proposals(id) ON DELETE RESTRICT,
 worker_run_id uuid REFERENCES public.worker_runs(id) ON DELETE SET NULL,
 attempt_number integer NOT NULL CHECK(attempt_number > 0),
 status text NOT NULL CHECK(status IN('started','succeeded','failed','blocked','stale','rolled_back')),
 started_at timestamptz NOT NULL DEFAULT now(), finished_at timestamptz,
 applied_by text NOT NULL CHECK(btrim(applied_by) <> ''),
 failure_code text, failure_summary text, transaction_id bigint,
 proposal_input_hash text NOT NULL, operation text NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(proposal_id,attempt_number)
);
CREATE UNIQUE INDEX integration_apply_one_success_uidx ON public.integration_apply_attempts(proposal_id) WHERE status='succeeded';
CREATE INDEX integration_apply_attempt_status_idx ON public.integration_apply_attempts(status,created_at DESC);

CREATE TABLE public.integration_apply_changes (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 apply_attempt_id bigint NOT NULL REFERENCES public.integration_apply_attempts(id) ON DELETE RESTRICT,
 entity_type text NOT NULL, entity_id text,
 table_name text NOT NULL, operation text NOT NULL,
 key_json jsonb NOT NULL, before_json jsonb, after_json jsonb NOT NULL,
 change_hash text NOT NULL, rollback_payload_json jsonb NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(apply_attempt_id,change_hash)
);
CREATE INDEX integration_apply_changes_entity_idx ON public.integration_apply_changes(entity_type,entity_id);

DO $security$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['integration_apply_attempts','integration_apply_changes'] LOOP
  EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t);
  EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY',t);
  EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC,anon,authenticated',t);
  EXECUTE format('GRANT SELECT,INSERT,UPDATE ON public.%I TO service_role',t);
  EXECUTE format('REVOKE DELETE ON public.%I FROM service_role',t);
 END LOOP;
END $security$;
GRANT USAGE,SELECT ON SEQUENCE public.integration_apply_attempts_id_seq,public.integration_apply_changes_id_seq TO service_role;
INSERT INTO public.schema_migrations(version,filename) VALUES('024','024_apply_integration_worker.sql') ON CONFLICT(version) DO NOTHING;
COMMIT;
