-- PR 3A: internal content drafts only; no validation, approval, or publication.
BEGIN;
ALTER TABLE public.content_backlog ADD COLUMN content_assembly_state text NOT NULL DEFAULT 'not_ready'
 CHECK(content_assembly_state IN('not_ready','ready_for_content_assembly','content_draft_created','content_draft_partial','content_draft_blocked','needs_content_validation','out_of_scope'));
CREATE TABLE public.content_drafts (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, site_id text NOT NULL REFERENCES public.sites(id) ON DELETE RESTRICT,
 environment text NOT NULL CHECK(environment IN('development','staging','production')), worker_run_id uuid REFERENCES public.worker_runs(id) ON DELETE SET NULL,
 backlog_item_id bigint NOT NULL REFERENCES public.content_backlog(id) ON DELETE RESTRICT, entity_type text NOT NULL, entity_id text NOT NULL, locale text NOT NULL,
 draft_type text NOT NULL CHECK(draft_type IN('model_overview','error_code_description','fault_summary','troubleshooting_guide','translation','faq_candidate')),
 template_id text NOT NULL, template_version text NOT NULL, status text NOT NULL CHECK(status IN('assembled','partial','blocked','superseded')),
 risk_level text NOT NULL CHECK(risk_level IN('low','medium','high','safety_review')),
 comparison_class text NOT NULL CHECK(comparison_class IN('new_draft','fills_missing_section','updates_existing_draft','same_as_existing','conflicts_with_existing','would_remove_information','translation_stale')),
 source_input_hash text NOT NULL, content_hash text NOT NULL, rendered_content_json jsonb NOT NULL CHECK(jsonb_typeof(rendered_content_json)='object'),
 assembler_version text NOT NULL, validation_state text NOT NULL DEFAULT 'pending' CHECK(validation_state IN('pending','needs_review','blocked')),
 review_state text NOT NULL DEFAULT 'unreviewed' CHECK(review_state IN('unreviewed','rejected','approved')),
 supersedes_draft_id bigint REFERENCES public.content_drafts(id) ON DELETE RESTRICT, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(backlog_item_id,entity_type,entity_id,locale,draft_type,template_id,template_version,source_input_hash,assembler_version)
);
CREATE INDEX content_drafts_review_idx ON public.content_drafts(site_id,environment,status,validation_state,review_state);
CREATE TABLE public.content_draft_sections (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, content_draft_id bigint NOT NULL REFERENCES public.content_drafts(id) ON DELETE RESTRICT,
 section_key text NOT NULL, sort_order integer NOT NULL, section_status text NOT NULL CHECK(section_status IN('assembled','omitted_no_data','blocked_conflict','blocked_missing_evidence','needs_review')),
 content_json jsonb NOT NULL, required boolean NOT NULL, input_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(content_draft_id,section_key)
);
CREATE TABLE public.content_draft_evidence (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, content_draft_id bigint NOT NULL REFERENCES public.content_drafts(id) ON DELETE RESTRICT,
 content_draft_section_id bigint REFERENCES public.content_draft_sections(id) ON DELETE RESTRICT, fact_type text NOT NULL, entity_type text NOT NULL, entity_id text,
 candidate_fact_id bigint REFERENCES public.candidate_facts(id) ON DELETE RESTRICT, source_evidence_id bigint REFERENCES public.source_evidence(id) ON DELETE RESTRICT,
 source_document_id bigint REFERENCES public.source_documents(id) ON DELETE RESTRICT, support_type text NOT NULL CHECK(support_type IN('direct_fact','derived_formatting','cautious_summary','context')),
 locator_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), CHECK(candidate_fact_id IS NOT NULL OR source_evidence_id IS NOT NULL OR source_document_id IS NOT NULL)
);
CREATE TABLE public.content_draft_issues (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, content_draft_id bigint NOT NULL REFERENCES public.content_drafts(id) ON DELETE RESTRICT,
 section_key text, issue_type text NOT NULL CHECK(issue_type IN('missing_required_fact','conflicting_fact','insufficient_procedure','missing_locale_source','safety_review_required','template_input_invalid','unsupported_claim')),
 severity text NOT NULL CHECK(severity IN('low','medium','high','safety_review')), details_json jsonb NOT NULL,
 status text NOT NULL DEFAULT 'open' CHECK(status IN('open','resolved','dismissed')), created_at timestamptz NOT NULL DEFAULT now(), resolved_at timestamptz
);
DO $security$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['content_drafts','content_draft_sections','content_draft_evidence','content_draft_issues'] LOOP
  EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY',t);
  EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC,anon,authenticated',t); EXECUTE format('GRANT SELECT,INSERT,UPDATE ON public.%I TO service_role',t); EXECUTE format('REVOKE DELETE ON public.%I FROM service_role',t);
 END LOOP;
END $security$;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
INSERT INTO public.schema_migrations(version,filename) VALUES('025','025_content_assembly_worker.sql') ON CONFLICT(version) DO NOTHING;
COMMIT;
