-- PR 3B: immutable validation findings; no draft content mutation or publication.
BEGIN;
ALTER TABLE public.content_drafts DROP CONSTRAINT content_drafts_validation_state_check;
UPDATE public.content_drafts SET validation_state=CASE validation_state
 WHEN 'needs_review' THEN 'validation_needs_review'
 WHEN 'blocked' THEN 'validation_failed'
 ELSE validation_state END;
ALTER TABLE public.content_drafts ADD CONSTRAINT content_drafts_validation_state_check
 CHECK(validation_state IN('pending','validation_passed','validation_needs_review','validation_failed','validation_stale'));
ALTER TABLE public.content_backlog ADD COLUMN content_validation_state text NOT NULL DEFAULT 'not_validated'
 CHECK(content_validation_state IN('not_validated','content_validation_passed','content_validation_needs_review','content_validation_failed'));
CREATE TABLE public.content_validation_runs (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, site_id text NOT NULL REFERENCES public.sites(id) ON DELETE RESTRICT,
 environment text NOT NULL CHECK(environment IN('development','staging','production')), worker_run_id uuid REFERENCES public.worker_runs(id) ON DELETE SET NULL,
 content_draft_id bigint NOT NULL REFERENCES public.content_drafts(id) ON DELETE RESTRICT, validator_version text NOT NULL,
 ruleset_id text NOT NULL, ruleset_version text NOT NULL, input_content_hash text NOT NULL, evidence_hash text NOT NULL, validation_identity_hash text NOT NULL UNIQUE,
 status text NOT NULL CHECK(status IN('running','completed','failed','blocked')), started_at timestamptz NOT NULL DEFAULT now(), finished_at timestamptz, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX content_validation_runs_draft_idx ON public.content_validation_runs(content_draft_id,created_at DESC);
CREATE TABLE public.content_validation_results (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, validation_run_id bigint NOT NULL UNIQUE REFERENCES public.content_validation_runs(id) ON DELETE RESTRICT,
 content_draft_id bigint NOT NULL REFERENCES public.content_drafts(id) ON DELETE RESTRICT,
 overall_result text NOT NULL CHECK(overall_result IN('pass','needs_review','fail')),
 claim_result text NOT NULL, structure_result text NOT NULL, translation_result text NOT NULL, duplication_result text NOT NULL, safety_result text NOT NULL, publication_readiness_result text NOT NULL,
 risk_level text NOT NULL CHECK(risk_level IN('low','medium','high','safety_review')), summary_json jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.content_claim_checks (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, validation_run_id bigint NOT NULL REFERENCES public.content_validation_runs(id) ON DELETE RESTRICT,
 content_draft_section_id bigint REFERENCES public.content_draft_sections(id) ON DELETE RESTRICT, claim_key text NOT NULL, claim_text_hash text NOT NULL,
 claim_type text NOT NULL, result text NOT NULL CHECK(result IN('supported','partially_supported','unsupported','conflicted','not_a_factual_claim')),
 supporting_evidence_count integer NOT NULL CHECK(supporting_evidence_count>=0), reason_code text NOT NULL, details_json jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.content_safety_findings (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, validation_run_id bigint NOT NULL REFERENCES public.content_validation_runs(id) ON DELETE RESTRICT,
 content_draft_section_id bigint REFERENCES public.content_draft_sections(id) ON DELETE RESTRICT, safety_type text NOT NULL,
 severity text NOT NULL CHECK(severity IN('low','medium','high','safety_review')), review_required boolean NOT NULL, details_json jsonb NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(), resolved_at timestamptz
);
CREATE TABLE public.content_duplication_findings (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, validation_run_id bigint NOT NULL REFERENCES public.content_validation_runs(id) ON DELETE RESTRICT,
 content_draft_section_id bigint REFERENCES public.content_draft_sections(id) ON DELETE RESTRICT, matched_entity_type text, matched_entity_id text,
 match_type text NOT NULL CHECK(match_type IN('exact_duplicate','normalized_duplicate','procedure_duplicate','template_only_duplicate','identifier_substitution_duplicate')),
 similarity_value numeric(6,5) NOT NULL CHECK(similarity_value BETWEEN 0 AND 1), severity text NOT NULL CHECK(severity IN('low','medium','high')),
 details_json jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
DO $security$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['content_validation_runs','content_validation_results','content_claim_checks','content_safety_findings','content_duplication_findings'] LOOP
  EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY',t);
  EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC,anon,authenticated',t); EXECUTE format('GRANT SELECT,INSERT,UPDATE ON public.%I TO service_role',t); EXECUTE format('REVOKE DELETE ON public.%I FROM service_role',t);
 END LOOP;
END $security$;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
INSERT INTO public.schema_migrations(version,filename) VALUES('026','026_content_validation_safety_worker.sql') ON CONFLICT(version) DO NOTHING;
COMMIT;
