-- Gate B: auditable one-at-a-time source decisions and missing role grants.
BEGIN;

CREATE TABLE public.source_candidate_reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_candidate_id bigint NOT NULL REFERENCES public.source_candidates(id) ON DELETE RESTRICT,
    decision text NOT NULL CHECK(decision IN('accepted','rejected')),
    reviewed_by text NOT NULL CHECK(NULLIF(btrim(reviewed_by),'') IS NOT NULL),
    review_reason text NOT NULL CHECK(NULLIF(btrim(review_reason),'') IS NOT NULL),
    reviewed_at timestamptz NOT NULL DEFAULT now(),
    decision_key text NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX source_candidate_reviews_candidate_idx
    ON public.source_candidate_reviews(source_candidate_id,reviewed_at DESC,id DESC);

CREATE OR REPLACE FUNCTION public.apply_source_candidate_review()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    UPDATE public.source_candidates
       SET status=NEW.decision,updated_at=now()
     WHERE id=NEW.source_candidate_id;
    IF NOT FOUND THEN RAISE EXCEPTION 'source candidate not found'; END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER source_candidate_review_apply
AFTER INSERT ON public.source_candidate_reviews
FOR EACH ROW EXECUTE FUNCTION public.apply_source_candidate_review();

ALTER TABLE public.source_candidate_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.source_candidate_reviews FORCE ROW LEVEL SECURITY;
REVOKE ALL ON public.source_candidate_reviews FROM PUBLIC,anon,authenticated;
GRANT SELECT,INSERT ON public.source_candidate_reviews TO service_role;
REVOKE UPDATE,DELETE,TRUNCATE ON public.source_candidate_reviews FROM service_role;
GRANT USAGE,SELECT ON SEQUENCE public.source_candidate_reviews_id_seq TO service_role;

GRANT SELECT ON public.scrape_jobs,public.schema_migrations TO service_role;
GRANT SELECT ON public.brands,public.categories,public.category_translations,
    public.models,public.articles,public.article_translations TO anon,authenticated;

INSERT INTO public.schema_migrations(version,filename)
VALUES('027','027_gate_b_source_review.sql') ON CONFLICT(version) DO NOTHING;
NOTIFY pgrst,'reload schema';
COMMIT;
