export type Locale = 'en' | 'sv' | 'de' | 'fr' | 'es' | 'pl'

const ui = {
  en: {
    // Global
    'nav.home': 'Home',
    'lang.comingSoon': 'Coming soon',
    'lang.switchAriaLabel': 'Switch language',
    // Severity
    'severity.easy': 'Easy',
    'severity.medium': 'Medium',
    'severity.advanced': 'Advanced',
    // Category page
    'category.intro': 'Select your brand to find error code guides for your {category}.',
    'category.noBrands': 'No brands available yet. Please check back soon.',
    'category.h1': '{category} Error Codes',
    // Brand page
    'brand.intro': 'Browse all known error codes for {brand} {category}s, then jump to your specific model below.',
    'brand.noErrorCodeCallout': 'No error code?',
    'brand.browseProblems': 'Browse symptom-based guides for common {brand} {category} problems.',
    'brand.errorCodesHeading': 'Error Codes',
    'brand.searchCodes': 'Search codes…',
    'brand.titlePlaceholder': 'Diagnostic title coming soon',
    'brand.guideLink': 'Full troubleshooting guide →',
    'brand.guidePending': 'Guide coming soon',
    'brand.browseModels': 'Browse {brand} {category} models',
    'brand.modelsPanelSub': 'Select your model to see error codes and troubleshooting guides.',
    'brand.searchModels': 'Search models…',
    'brand.noResults': 'No error codes found yet. Check back soon.',
    'brand.h1': '{brand} {category} Troubleshooting',
    'brand.faultsHeading': 'Faults',
    'brand.modelsHeading': 'Product models',
    'brand.faultsViewAll': 'View all {brand} {category} faults →',
    // Problems listing page
    'problems.breadcrumb': 'Common Problems',
    'problems.heading': 'Common {brand} {category} Problems',
    'problems.intro': 'Find your symptom below for a step-by-step diagnosis and repair guide.',
    'problems.noData': 'No common problems listed yet. Check back soon.',
    'problems.backLink': '← Back to {brand} {category} error codes',
    // Article / slug page
    'article.updatedAt': 'Updated {date}',
    'article.professionalRepair': 'Professional repair recommended',
    'article.faultDescription': 'Fault description',
    'article.causes': 'Causes',
    'article.freqCommon': 'Most common',
    'article.freqOccasional': 'Occasional',
    'article.freqRare': 'Rare',
    'article.affectedModels': 'Affected models',
    'article.expandModels': 'Expand to see affected models',
    'article.modelPanelSub': 'Select your model to see its full troubleshooting page.',
    'article.searchModels': 'Search models…',
    'article.series': '{name} series',
    'article.modelCount': '{n} models',
    'article.whenToCallTech': 'When to call a service technician',
    'article.notAvailable': 'Content not available yet. Please check back soon.',
    'article.errorCodeLabel': 'Error Code {code}',
    // Model page sections (within article slug page)
    'model.overview': 'Model overview',
    'model.commonFaults': 'Common faults',
    'model.errorCodes': 'Error codes',
    'model.variants': 'Model variants',
    'model.specification': 'Specification',
    'model.spareParts': 'Spare parts and service',
    'model.released': 'Released {year}',
    'model.contents': 'Contents',
    'model.noFaults': 'No common faults listed yet.',
    'model.allProblems': 'See all {brand} {category} problems →',
    'model.noErrorCodes': 'No error codes found yet for this model. Check back soon.',
    'model.noVariants': 'No other models in this series.',
    // Problems/faults article page
    'faultArticle.relatedErrorCodes': 'Related error codes',
    'faultArticle.prevention': 'Prevention',
    // Components
    'quickfix.label': 'Quick Fix',
    'steps.heading': 'Step-by-Step Fix',
    'steps.genericWarning': 'Take care with this step.',
    'faq.heading': 'Frequently Asked Questions',
    // Homepage sections
    'home.browseByType': 'Browse by appliance type',
    'home.commonFaults': 'Common faults — what are you seeing?',
    'home.commonFaultsSub': 'No error code? Browse by symptom.',
    'home.popularBrands': 'Popular brands',
    'home.allBrands': 'All brands →',
    'home.trending': 'Trending error codes',
    'home.popular': 'Popular guides',
    'home.howItWorks': 'How it works',
    'home.step1Title': 'Select your appliance and brand',
    'home.step1Desc': 'Or enter the error code directly',
    'home.step2Title': 'Find your error code or symptom',
    'home.step2Desc': 'Pick from the list or search',
    'home.step3Title': 'Follow the fix steps',
    'home.step3Desc': 'Free guides, no sign-up needed',
    'home.heroH1': 'Fix Appliance Error Codes Fast',
    'home.heroSub': 'Step-by-step troubleshooting guides for Samsung, Bosch, LG, Siemens and more. Free DIY fixes written by appliance repair experts.',
    'home.noCategories': 'No categories yet. Check back soon.',
    'home.browseByBrand': 'Browse by Brand',
    'hero.tagline': 'Fix appliance error codes — free step-by-step guides',
    'hero.subtext': 'Written by appliance technicians. No sign-up needed.',
    'hero.tabError': 'An error code',
    'hero.tabFault': 'A symptom / fault',
    'hero.applianceType': 'Appliance type',
    'hero.brand': 'Brand',
    'hero.selectAppliance': 'Select appliance…',
    'hero.selectBrand': 'Select brand…',
    'hero.errorCode': 'Error code',
    'hero.errorCodePlaceholder': 'e.g. 4E, F21…',
    'hero.findFix': 'Find fix →',
    // SEO meta templates (used in page <title> and <meta description>)
    'meta.siteTagline': 'Fix Appliance Error Codes Fast',
    'meta.categoryTitle': '{category} Error Codes – All Brands',
    'meta.categoryDesc': 'Find error code fixes for all {category} brands. Step-by-step DIY guides.',
    'meta.brandTitle': '{brand} {category} Error Codes & Troubleshooting',
    'meta.brandDesc': 'All {brand} {category} error codes with step-by-step fixes, plus a full model list.',
    // Model page H1
    'model.h1': '{brand} {model} – Error Codes & Troubleshooting',
    // 404 page
    '404.title': 'Page not found',
    '404.heading': "Sorry, we couldn't find this page.",
    '404.body': "But don't worry, you can find plenty of other things on our homepage.",
    '404.backButton': 'Back to homepage',
    // Spare parts section
    'spareParts.heading': 'Spare parts and service',
    'spareParts.sub': 'Visit our partners for spare parts and service',
    'spareParts.partsHeading': 'Spare parts',
    'spareParts.repairHeading': 'Book a repair',
    // Specs table labels
    'specs.doorType': 'Door type',
    'specs.frontLoad': 'Front load',
    'specs.topLoad': 'Top load',
    'specs.drumCapacity': 'Drum capacity',
    'specs.maxSpinSpeed': 'Max spin speed',
    'specs.energyClass': 'Energy class',
    'specs.width': 'Width',
    'specs.height': 'Height',
    'specs.depth': 'Depth',
    'specs.noiseSpin': 'Noise (spin)',
    'specs.energyConsumption': 'Energy consumption',
    'specs.waterConsumption': 'Water consumption',
    // Brand hub page
    'brandHub.h1': '{brand} Appliance Troubleshooting',
    'brandHub.intro': 'Select your appliance type to browse error codes and fault guides for {brand}.',
    'brandHub.noGuides': 'No repair guides available yet for {brand}.',
    'brandHub.cta': 'Not what you\'re looking for? Browse all brands →',
    'brandHub.allBrandsH1': 'All appliance brands',
    'brandHub.allBrandsIntro': 'Select your brand to browse error codes and repair guides.',
    'brandHub.hubLink': 'All {brand} appliances →',
    'brandHub.appliancesHeading': 'Appliances',
    // Model index page
    'models.h1': '{brand} {category} Models',
    'models.intro': 'Select your model to see error codes and troubleshooting guides.',
    'models.noModels': 'No models listed yet.',
    'models.backLink': '← Back to {brand} {category}',
    'models.meta.title': '{brand} {category} Models – Full List',
    'models.meta.desc': 'Browse all {brand} {category} models. Find your model for error codes and repair guides.',
  },
  sv: {
    'nav.home': 'Hem',
    'lang.comingSoon': 'Kommer snart',
    'lang.switchAriaLabel': 'Byt språk',
    'severity.easy': 'Enkel',
    'severity.medium': 'Medel',
    'severity.advanced': 'Avancerad',
    'category.intro': 'Välj ditt märke för att hitta felkodsguider för din {category}.',
    'category.noBrands': 'Inga märken tillgängliga ännu. Kom tillbaka snart.',
    'category.h1': '{category} Felkoder',
    'brand.intro': 'Bläddra bland alla kända felkoder för {brand} {category}. Hoppa till din specifika modell nedan.',
    'brand.noErrorCodeCallout': 'Ingen felkod?',
    'brand.browseProblems': 'Bläddra bland symptombaserade guider för vanliga {brand} {category}-problem.',
    'brand.errorCodesHeading': 'Felkoder',
    'brand.searchCodes': 'Sök felkoder…',
    'brand.titlePlaceholder': 'Diagnostisk titel kommer snart',
    'brand.guideLink': 'Fullständig felsökningsguide →',
    'brand.guidePending': 'Guide kommer snart',
    'brand.browseModels': 'Bläddra bland {brand} {category}-modeller',
    'brand.modelsPanelSub': 'Välj din modell för att se felkoder och felsökningsguider.',
    'brand.searchModels': 'Sök modeller…',
    'brand.noResults': 'Inga felkoder hittades ännu. Kom tillbaka snart.',
    'brand.h1': '{brand} {category} Felsökning',
    'brand.faultsHeading': 'Fel',
    'brand.modelsHeading': 'Produktmodeller',
    'brand.faultsViewAll': 'Se alla {brand} {category}-fel →',
    'problems.breadcrumb': 'Vanliga problem',
    'problems.heading': 'Vanliga {brand} {category}-problem',
    'problems.intro': 'Hitta ditt symptom nedan för en steg-för-steg-diagnos och reparationsguide.',
    'problems.noData': 'Inga vanliga problem listade ännu. Kom tillbaka snart.',
    'problems.backLink': '← Tillbaka till {brand} {category}-felkoder',
    'article.updatedAt': 'Uppdaterad {date}',
    'article.professionalRepair': 'Professionell reparation rekommenderas',
    'article.faultDescription': 'Felbeskrivning',
    'article.causes': 'Orsaker',
    'article.freqCommon': 'Vanligast',
    'article.freqOccasional': 'Ibland',
    'article.freqRare': 'Sällsynt',
    'article.affectedModels': 'Berörda modeller',
    'article.expandModels': 'Expandera för att se berörda modeller',
    'article.modelPanelSub': 'Välj din modell för att se dess fullständiga felsökningssida.',
    'article.searchModels': 'Sök modeller…',
    'article.series': '{name}-serien',
    'article.modelCount': '{n} modeller',
    'article.whenToCallTech': 'När ska du ringa en servicetekniker',
    'article.notAvailable': 'Innehåll inte tillgängligt ännu. Kom tillbaka snart.',
    'article.errorCodeLabel': 'Felkod {code}',
    'model.overview': 'Modellöversikt',
    'model.commonFaults': 'Vanliga fel',
    'model.errorCodes': 'Felkoder',
    'model.variants': 'Modellvarianter',
    'model.specification': 'Specifikation',
    'model.spareParts': 'Reservdelar och service',
    'model.released': 'Lanserad {year}',
    'model.contents': 'Innehåll',
    'model.noFaults': 'Inga vanliga fel listade ännu.',
    'model.allProblems': 'Se alla {brand} {category}-problem →',
    'model.noErrorCodes': 'Inga felkoder hittades ännu för denna modell. Kom tillbaka snart.',
    'model.noVariants': 'Inga andra modeller i denna serie.',
    'quickfix.label': 'Snabbfix',
    'steps.heading': 'Steg-för-steg-reparation',
    'steps.genericWarning': 'Var försiktig med det här steget.',
    'faq.heading': 'Vanliga frågor',
    'home.browseByType': 'Bläddra efter apparattyp',
    'home.commonFaults': 'Vanliga fel — vad ser du?',
    'home.commonFaultsSub': 'Ingen felkod? Bläddra efter symptom.',
    'home.popularBrands': 'Populära märken',
    'home.allBrands': 'Alla märken →',
    'home.trending': 'Populära felkoder just nu',
    'home.popular': 'Populära guider',
    'home.howItWorks': 'Hur det fungerar',
    'home.step1Title': 'Välj din apparat och ditt märke',
    'home.step1Desc': 'Eller ange felkoden direkt',
    'home.step2Title': 'Hitta din felkod eller symptom',
    'home.step2Desc': 'Välj från listan eller sök',
    'home.step3Title': 'Följ reparationsstegen',
    'home.step3Desc': 'Kostnadsfria guider, ingen registrering behövs',
    'home.heroH1': 'Laga hushållsapparaters felkoder – snabbt',
    'home.heroSub': 'Steg-för-steg-felsökningsguider för Samsung, Bosch, LG, Siemens och fler. Kostnadsfria DIY-reparationer skrivna av experter på vitvaror.',
    'home.noCategories': 'Inga kategorier ännu. Kom tillbaka snart.',
    'home.browseByBrand': 'Bläddra efter märke',
    'hero.tagline': 'Laga felkoder på hushållsapparater — kostnadsfria steg-för-steg-guider',
    'hero.subtext': 'Skrivet av vitvarutekniker. Inget konto behövs.',
    'hero.tabError': 'En felkod',
    'hero.tabFault': 'Ett symptom / fel',
    'hero.applianceType': 'Apparattyp',
    'hero.brand': 'Märke',
    'hero.selectAppliance': 'Välj apparat…',
    'hero.selectBrand': 'Välj märke…',
    'hero.errorCode': 'Felkod',
    'hero.errorCodePlaceholder': 't.ex. 4E, F21…',
    'hero.findFix': 'Hitta lösning →',
    'meta.siteTagline': 'Laga hushållsapparaters felkoder – snabbt',
    'meta.categoryTitle': '{category} Felkoder – Alla märken',
    'meta.categoryDesc': 'Hitta felkodsguider för alla {category}-märken. Steg-för-steg-guider för hemmareparation.',
    'meta.brandTitle': '{brand} {category} Felkoder & Felsökning',
    'meta.brandDesc': 'Alla {brand} {category}-felkoder med steg-för-steg-guider, plus en komplett modelllista.',
    'model.h1': '{brand} {model} – Felkoder & Felsökning',
    '404.title': 'Sidan hittades inte',
    '404.heading': 'Tyvärr hittade vi inte den här sidan.',
    '404.body': 'Men oroa dig inte, det finns mycket annat på vår startsida.',
    '404.backButton': 'Tillbaka till startsidan',
    'spareParts.heading': 'Reservdelar och service',
    'spareParts.sub': 'Besök våra partners för reservdelar och service',
    'spareParts.partsHeading': 'Reservdelar',
    'spareParts.repairHeading': 'Boka reparation',
    'specs.doorType': 'Lucköppning',
    'specs.frontLoad': 'Frontmatad',
    'specs.topLoad': 'Toppmatad',
    'specs.drumCapacity': 'Trumkapacitet',
    'specs.maxSpinSpeed': 'Max centrifugeringshastighet',
    'specs.energyClass': 'Energiklass',
    'specs.width': 'Bredd',
    'specs.height': 'Höjd',
    'specs.depth': 'Djup',
    'specs.noiseSpin': 'Buller (centrifugering)',
    'specs.energyConsumption': 'Energiförbrukning',
    'specs.waterConsumption': 'Vattenförbrukning',
    'brandHub.h1': '{brand} Apparatfelsökning',
    'brandHub.intro': 'Välj din apparattyp för att bläddra bland felkoder och felsymtomguider för {brand}.',
    'brandHub.noGuides': 'Inga reparationsguider tillgängliga ännu för {brand}.',
    'brandHub.cta': 'Hittade du inte det du sökte? Bläddra bland alla märken →',
    'brandHub.allBrandsH1': 'Alla apparatmärken',
    'brandHub.allBrandsIntro': 'Välj ditt märke för att bläddra bland felkoder och reparationsguider.',
    'brandHub.hubLink': 'Alla {brand} apparater →',
    'brandHub.appliancesHeading': 'Apparater',
    'models.h1': '{brand} {category} modeller',
    'models.intro': 'Välj din modell för att se felkoder och felsökningsguider.',
    'models.noModels': 'Inga modeller listade ännu.',
    'models.backLink': '← Tillbaka till {brand} {category}',
    'models.meta.title': '{brand} {category} modeller – Komplett lista',
    'models.meta.desc': 'Bläddra bland alla {brand} {category}-modeller. Hitta din modell för felkoder och reparationsguider.',
  },
  de: {},
  fr: {},
  es: {},
  pl: {},
} as const

type UiKeys = keyof typeof ui.en

export function t(locale: string, key: UiKeys, vars?: Record<string, string>): string {
  const dict = (ui as any)[locale] ?? {}
  let str: string = dict[key] ?? ui.en[key] ?? key
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      str = str.replaceAll(`{${k}}`, v)
    }
  }
  return str
}
