"""Build reviewed Samsung spin/drum/control/electrical fault content."""
from __future__ import annotations
import json
from config.settings import BASE_DIR
from pipeline.build_p0_batch_002_deterministic import build_en,build_sv

ITEMS={
138:("wet","clothes are still wet after spinning","kläderna är fortfarande våta efter centrifugering","Samsung Clothes Still Wet After Spin: Safe Checks","Samsung-kläder fortfarande våta: säkra kontroller"),
141:("drum","drum is not turning","trumman snurrar inte","Samsung Washing Machine Drum Not Turning: Safe Steps","Samsung-tvättmaskinens trumma snurrar inte: säkra steg"),
142:("panel","control panel is unresponsive","kontrollpanelen svarar inte","Samsung Washer Control Panel Unresponsive: Safe Checks","Samsung-tvättmaskinens panel svarar inte: säkra kontroller"),
146:("breaker","trips the electrical protection","löser ut elskyddet","Samsung Washer Trips the Electrics: Stop and Get Help","Samsung-tvättmaskinen löser ut elskyddet: stoppa"),
147:("burning","has a burning smell","har en bränd lukt","Samsung Washer Burning Smell: Stop and Get Help","Samsung-tvättmaskin luktar bränt: stoppa och få hjälp"),
}
DATA={
"wet":("Samsung links soaking-wet laundry to poor spinning, often caused by an unbalanced load, drainage restriction, unsuitable cycle or an unlevel washer","Samsung kopplar genomvåt tvätt till bristfällig centrifugering, ofta på grund av obalanserad last, begränsad tömning, olämpligt program eller en maskin som inte står plant","Redistribute the load, verify the cycle and level, and check the visible drain hose and user-accessible filter according to the exact manual","Fördela lasten, kontrollera program och nivå och kontrollera synlig avloppsslang och användaråtkomligt filter enligt exakt manual"),
"drum":("Samsung advises service when the drum does not turn during either washing or spinning after basic load and drainage checks","Samsung rekommenderar service när trumman inte snurrar under vare sig tvätt eller centrifugering efter grundläggande last- och tömningskontroller","Stop the washer, record any code and arrange Samsung service if the drum remains stationary; do not force or dismantle it","Stoppa maskinen, dokumentera eventuell kod och boka Samsung-service om trumman står stilla; tvinga eller demontera den inte"),
"panel":("Samsung identifies Child Lock, moisture on controls, unavailable cycle options or a temporary control condition as common reasons for unresponsive buttons","Samsung anger barnlås, fukt på reglagen, otillgängliga programval eller ett tillfälligt styrtillstånd som vanliga orsaker till svarslösa knappar","Check the Child Lock indicator and selected cycle, let the external panel dry and power-cycle the washer for 60 seconds once","Kontrollera barnlåsindikering och valt program, låt den yttre panelen torka och bryt strömmen till maskinen i 60 sekunder en gång"),
"breaker":("Repeated operation of an electrical protective device can indicate a supply, cord, outlet or internal appliance fault and must not be bypassed","Upprepad utlösning av ett elskydd kan tyda på fel i matning, sladd, uttag eller maskin och får inte kringgås","Leave the washer off, do not reset the protection to retry it and arrange a qualified electrician or Samsung service as appropriate","Låt maskinen vara avstängd, återställ inte skyddet för att prova igen och anlita behörig elektriker eller Samsung-service efter behov"),
"burning":("Samsung says to switch the washer off immediately when a burning odour occurs; smoke, melting or abnormal heat requires urgent isolation","Samsung anger att tvättmaskinen ska stängas av omedelbart vid bränd lukt; rök, smältning eller onormal värme kräver akut frånkoppling","Stop the washer and isolate power from a safe location; do not restart, open panels or clean a filter until the appliance has been professionally assessed","Stoppa maskinen och bryt strömmen från en säker plats; starta inte om, öppna inga paneler och rengör inget filter innan maskinen bedömts professionellt"),
}
CAUSES={
"wet":(["Unbalanced or unsuitable load","Restricted drainage","Washer is not level","Internal pump, motor, sensor or control fault"],["Obalanserad eller olämplig last","Begränsad tömning","Maskinen står inte plant","Internt fel i pump, motor, sensor eller styrning"]),
"drum":(["Water has not drained","Load or obstruction prevents safe movement","Motor information code","Internal drive, bearing, sensor or control fault"],["Vattnet har inte tömts","Last eller hinder förhindrar säker rörelse","Informationskod för motor","Internt fel i drivning, lager, sensor eller styrning"]),
"panel":(["Child Lock is enabled","Moisture or residue on external controls","Option unavailable for the selected cycle","Button, power-supply or control fault"],["Barnlåset är aktiverat","Fukt eller rester på yttre reglage","Valet är inte tillgängligt för programmet","Fel i knapp, strömförsörjning eller styrning"]),
"breaker":(["Damaged cord, plug or outlet","Unsuitable or faulty electrical supply","Moisture or insulation fault","Internal motor, heater, wiring or control fault"],["Skadad sladd, kontakt eller uttag","Olämplig eller felaktig elmatning","Fukt- eller isolationsfel","Internt fel i motor, värmare, kablage eller styrning"]),
"burning":(["Overheated plug, cord or outlet","Stalled motor or pump","Friction or overheating inside the appliance","Internal wiring or electronics fault"],["Överhettad kontakt, sladd eller uttag","Blockerad motor eller pump","Friktion eller överhettning i maskinen","Internt kablage- eller elektronikfel"]),
}

def faq(label,action,sv,urgent):
 if sv:return [{"question":f"Kan jag fortsätta när maskinen {label}?","answer":action+". "+("Maskinen får inte startas om innan den bedömts professionellt." if urgent else "Avbryt om problemet kvarstår eller återkommer.")},{"question":"Kan jag öppna maskinen och kontrollera delar?","answer":"Nej. Ta inte bort paneler och rör eller mät inte motor, pump, värmare, kablage eller elektronik."},{"question":"Visar symtomet vilken reservdel som behövs?","answer":"Nej. Exakt modell och professionell diagnos krävs innan någon del beställs."},{"question":"När behövs Samsung-service?","answer":"Boka service om säkra yttre kontroller inte räcker; vid elskydd eller bränd lukt ska maskinen förbli avstängd."},{"question":"När behövs elektriker?","answer":"Anlita behörig elektriker vid skadat uttag, kontakt, sladd eller återkommande utlöst elskydd."}]
 return [{"question":f"Can I continue when the washer {label}?","answer":action+". "+("Do not restart the appliance before professional assessment." if urgent else "Stop if the problem remains or returns.")},{"question":"May I open the washer and inspect parts?","answer":"No. Do not remove panels or touch or measure the motor, pump, heater, wiring or electronics."},{"question":"Does the symptom identify a replacement part?","answer":"No. The exact model and professional diagnosis are required before ordering any part."},{"question":"When is Samsung service needed?","answer":"Arrange service if safe external checks are insufficient; for tripped protection or burning smell, keep the washer off."},{"question":"When is an electrician needed?","answer":"Use a qualified electrician for a damaged outlet, plug or cord, or repeatedly tripped electrical protection."}]

def make(i,sv):
 kind,enlab,svlab,h1e,h1s=ITEMS[i];me,ms,ae,av=DATA[kind];meaning=ms if sv else me;action=av if sv else ae;urgent=kind in ('breaker','burning');v=build_sv(svlab,meaning,action) if sv else build_en(enlab,meaning,action);causes=[{"cause":x,"detail":("Detta är en möjlig orsak; interna fel kräver professionell diagnos för exakt modell." if sv else "This is a possible cause; internal faults require professional diagnosis for the exact model.")} for x in CAUSES[kind][1 if sv else 0]];h1=h1s if sv else h1e
 if sv:v.update({"title_tag":h1,"meta_description":f"Samsung-tvättmaskinen {svlab}? Läs säkra kontroller, tydliga stoppregler och när Samsung-service eller elektriker krävs.","h1":h1,"description":meaning[0].upper()+meaning[1:]+".","quick_fix":action+" (cirka 5–15 minuter för att säkra maskinen).","intro_html":f"<p>{meaning[0].upper()+meaning[1:]}.</p><p>{action}. Öppna inga paneler, gör inga mätningar och kringgå aldrig ett elskydd.</p>","causes_json":causes,"steps_json":[{"step":1,"action":"Stoppa säkert","detail":"Stoppa programmet. Vid bränd lukt, rök eller utlöst elskydd låter du maskinen vara avstängd och bryter strömmen från säker plats."},{"step":2,"action":"Dokumentera","detail":"Fotografera display och synliga symptom och anteckna modellnummer och när problemet uppstod."},{"step":3,"action":"Gör endast tillåten yttre kontroll","detail":action+". Rör inte skadad kontakt eller uttag och öppna inget hölje."},{"step":4,"action":"Avgör om återstart är tillåten","detail":("Återstart är inte tillåten vid detta symptom." if urgent else "Prova högst en gång efter korrigerad yttre orsak och endast utan säkerhetstecken.")},{"step":5,"action":"Ordna professionell hjälp","detail":"Boka Samsung-service för maskinfel och behörig elektriker vid misstänkt fel i uttag eller fast installation."}],"when_to_call_technician_html":"<p>Bränd lukt eller återkommande utlöst elskydd kräver stopp utan återstart. I övriga fall bokas Samsung-service om säkra yttre kontroller inte räcker.</p><p>Anlita behörig elektriker för skadat uttag eller fast elinstallation. Demontera inte maskinen.</p>","prevention_html":"<p>Följ last-, installations- och filteranvisningar, håll reglagen torra och använd avsedd jordad elanslutning utan olämpliga förlängningar.</p><p>Interna mekaniska och elektriska fel kan inte förebyggas genom demontering eller upprepade återställningar.</p>","faq_json":faq(svlab,action,True,urgent)})
 else:v.update({"title_tag":h1,"meta_description":f"Samsung washer {enlab}? Read safe checks, clear stop rules and when Samsung service or an electrician is required.","h1":h1,"description":meaning[0].upper()+meaning[1:]+".","quick_fix":action+" (about 5–15 minutes to make the washer safe).","intro_html":f"<p>{meaning[0].upper()+meaning[1:]}.</p><p>{action}. Open no panels, make no measurements and never bypass electrical protection.</p>","causes_json":causes,"steps_json":[{"step":1,"action":"Stop safely","detail":"Stop the programme. For burning smell, smoke or tripped protection, leave the washer off and isolate power from a safe location."},{"step":2,"action":"Record the symptom","detail":"Photograph the display and visible symptoms and note the model number and when the problem occurred."},{"step":3,"action":"Make only the permitted external check","detail":action+". Do not touch a damaged plug or outlet or open any enclosure."},{"step":4,"action":"Decide whether restart is permitted","detail":("Restart is not permitted for this symptom." if urgent else "Try no more than once after correcting an external cause and only without safety warning signs.")},{"step":5,"action":"Arrange professional help","detail":"Request Samsung service for an appliance fault and a qualified electrician for a suspected outlet or fixed-wiring fault."}],"when_to_call_technician_html":"<p>Burning smell or repeatedly tripped electrical protection requires stopping without restart. Otherwise arrange Samsung service when safe external checks are insufficient.</p><p>Use a qualified electrician for a damaged outlet or fixed installation. Do not dismantle the washer.</p>","prevention_html":"<p>Follow load, installation and filter instructions, keep controls dry and use the specified grounded electrical connection without unsuitable extensions.</p><p>Internal mechanical and electrical faults cannot be prevented through dismantling or repeated resets.</p>","faq_json":faq(enlab,action,False,urgent)})
 v['parts_json']=[];assert len(v['title_tag'])<=70 and len(v['meta_description'])<=165;return v

def main():
 b=json.loads((BASE_DIR/'data/backups/article_reviews/batch-030-samsung-spin-drum-controls-electrical-before.json').read_text(encoding='utf-8'));rows={(r['article_id'],r['locale']):r for r in b['rows']};o={"batch":"030-samsung-spin-drum-controls-electrical","status":"proposal_only_not_applied","article_ids":list(ITEMS),"sources":["https://www.samsung.com/uk/support/home-appliances/what-to-do-if-your-washing-machine-is-not-spinning/","https://www.samsung.com/us/support/troubleshoot/TSG10007308/","https://www.samsung.com/us/support/troubleshoot/TSG10007300/","https://www.samsung.com/ae/support/home-appliances/how-to-handle-a-burning-smell-in-your-washing-machine/","https://www.samsung.com/us/support/troubleshoot/TSG10007246/"],"translations":{}}
 for i,item in ITEMS.items():o['translations'][str(i)]={"code":item[1],"preserve":{"en_slug":rows[(i,'en')]['slug'],"sv_slug":rows[(i,'sv')]['slug']},"en":make(i,False),"sv":make(i,True)}
 p=BASE_DIR/'data/article_reviews/batch-030-samsung-spin-drum-controls-electrical-proposal.json';p.write_text(json.dumps(o,ensure_ascii=False,indent=2),encoding='utf-8');print(p)
if __name__=='__main__':main()
