"""Build reviewed Samsung dE/dE2/E/E1/FE content."""
from __future__ import annotations
import json
from config.settings import BASE_DIR
from pipeline.build_p0_batch_002_deterministic import build_en, build_sv

ITEMS={42:"dE",43:"dE2",45:"E",46:"E1",47:"FE"}

DATA={
42:("Samsung identifies dE as a door issue","Samsung anger att dE är ett luckproblem","Unplug the washer, remove trapped laundry and close the door firmly without forcing it","Dra ur kontakten, ta bort tvätt som har fastnat och stäng luckan ordentligt utan att tvinga den","door"),
43:("Samsung identifies dE2 as an on/off switch error","Samsung anger att dE2 är ett fel i strömbrytaren","Disconnect the washer from the mains for five minutes once and arrange Samsung service if dE2 returns","Koppla bort tvättmaskinen från elnätet i fem minuter en gång och boka Samsung-service om dE2 återkommer","switch"),
45:("A lone E is not defined in Samsung's generic public washer code table; its meaning depends on the exact model and complete display","En ensam E-kod definieras inte i Samsungs generella offentliga kodtabell för tvättmaskiner; betydelsen beror på exakt modell och hela displayen","Photograph the complete display and contact Samsung with the exact model number before assigning a meaning","Fotografera hela displayen och kontakta Samsung med exakt modellnummer innan koden ges en betydelse","unknown"),
46:("Samsung identifies E1 as a water-supply issue on applicable washer models","Samsung anger att E1 är ett fel i vattenförsörjningen på berörda tvättmaskinsmodeller","Open the tap fully, verify household flow and straighten the external inlet hose; clean the mesh filter only as the exact manual specifies","Öppna kranen helt, kontrollera vattenflödet och räta den yttre tilloppsslangen; rengör nätfiltret endast enligt exakt manual","fill"),
47:("Samsung identifies FE as a fan issue on applicable washer-dryer models","Samsung anger att FE är ett fläktfel på berörda kombinerade tvättmaskiner och torktumlare","Stop the appliance, switch it off and arrange Samsung service; do not open panels or reach the fan","Stoppa maskinen, stäng av den och boka Samsung-service; öppna inga paneler och försök inte nå fläkten","fan"),
}

CAUSES={
"door":(["Door not fully closed","Laundry trapped at the door","Load preventing closure","Door-lock or control fault"],["Luckan är inte helt stängd","Tvätt har fastnat vid luckan","Lasten hindrar stängning","Fel i lucklås eller styrning"]),
"switch":(["Temporary control condition","On/off control remains actuated","External control damage","Internal switch or electronics fault"],["Tillfälligt styrtillstånd","På/av-reglaget förblir aktiverat","Yttre skada på reglaget","Internt brytar- eller elektronikfel"]),
"unknown":(["Incomplete or misread display","Model-specific information code","A neighbouring character is not visible","Internal condition requiring Samsung diagnosis"],["Ofullständig eller feltolkad display","Modellspecifik informationskod","Ett intilliggande tecken syns inte","Internt tillstånd som kräver Samsung-diagnos"]),
"fill":(["Closed tap or water outage","Low water flow or pressure","Kinked inlet hose","Blocked mesh filter or internal inlet fault"],["Stängd kran eller vattenavbrott","Lågt vattenflöde eller tryck","Vikt tilloppsslang","Blockerat nätfilter eller internt inloppsfel"]),
"fan":(["Fan operation interrupted","Restricted model-specific airflow","Fan signal or wiring fault","Internal fan or control-electronics fault"],["Fläktdriften har avbrutits","Begränsat modellspecifikt luftflöde","Fel i fläktsignal eller kablage","Internt fläkt- eller elektronikfel"]),
}

def make(article_id:int,sv:bool)->dict:
 code=ITEMS[article_id]; me,ms,ae,av,kind=DATA[article_id]; meaning=ms if sv else me; action=av if sv else ae
 v=build_sv(code,meaning,action) if sv else build_en(code,meaning,action)
 causes=CAUSES[kind][1 if sv else 0]
 if sv:
  v.update({"title_tag":f"Samsung-tvättmaskin felkod {code}: säkra steg","meta_description":f"Visar Samsung-tvättmaskinen {code}? Läs verifierad betydelse, säkra yttre kontroller och när auktoriserad service krävs.","h1":f"Vad betyder {code} på en Samsung-tvättmaskin?","description":meaning[0].upper()+meaning[1:]+".","quick_fix":action+" (cirka 5–15 minuter).","intro_html":f"<p>{meaning[0].upper()+meaning[1:]}.</p><p>{action}. Öppna inga paneler, mät inga interna delar och beställ inte en reservdel från koden ensam.</p>","causes_json":[{"cause":x,"detail":"Detta är en möjlig orsak; exakt modellmanual och professionell diagnos avgör interna fel."} for x in causes],"steps_json":[{"step":1,"action":"Stoppa säkert","detail":"Pausa programmet, vänta tills trumman stannat och tvinga inte luckan."},{"step":2,"action":"Dokumentera exakt","detail":f"Fotografera hela {code}-visningen och anteckna modellnummer och programfas."},{"step":3,"action":"Gör endast säker yttre kontroll","detail":action+". Rör inte intern brytare, lås, fläkt, ventil, kablage eller elektronik."},{"step":4,"action":"Testa högst en gång","detail":"Starta endast efter korrigerad yttre orsak och aldrig vid läckage, bränd lukt, rök, onormal värme eller elskada."},{"step":5,"action":"Boka Samsung-service","detail":"Boka auktoriserad service om koden kvarstår eller återkommer. Demontera inget och gör inga elektriska mätningar."}],"when_to_call_technician_html":f"<p>Boka Samsung-service om {code} kvarstår eller återkommer efter säkra yttre kontroller. Lucklås, brytare, fläktar, ventiler, kablage och elektronik är inte användarreparationer.</p><p>Koppla ur direkt vid läckage nära el, bränd lukt, rök, gnistor, onormal värme eller utlöst elskydd.</p>","prevention_html":"<p>Följ lastgränser och installationsanvisningar, håll lucktätning och yttre reglage rena och torra och kontrollera synliga slangar enligt manualen.</p><p>Notera hela koden och modellnumret. Interna lås-, fläkt-, ventil- och elektronikfel kan inte förebyggas genom demontering.</p>"})
 else:
  v.update({"title_tag":f"Samsung Washing Machine Error {code}: Safe Steps","meta_description":f"Samsung washer showing {code}? Read the verified meaning, safe external checks and when authorised service is required.","h1":f"What Does {code} Mean on a Samsung Washing Machine?","description":meaning[0].upper()+meaning[1:]+".","quick_fix":action+" (about 5–15 minutes).","intro_html":f"<p>{meaning[0].upper()+meaning[1:]}.</p><p>{action}. Open no panels, measure no internal parts and do not order a part from the code alone.</p>","causes_json":[{"cause":x,"detail":"This is a possible cause; the exact model manual and professional diagnosis determine internal faults."} for x in causes],"steps_json":[{"step":1,"action":"Stop safely","detail":"Pause the programme, wait for the drum to stop and do not force the door."},{"step":2,"action":"Record exactly","detail":f"Photograph the complete {code} display and note the model number and programme stage."},{"step":3,"action":"Make only the safe external check","detail":action+". Do not touch an internal switch, lock, fan, valve, wiring or electronics."},{"step":4,"action":"Test no more than once","detail":"Restart only after correcting an external cause, and never with leakage, burning smell, smoke, abnormal heat or electrical damage."},{"step":5,"action":"Arrange Samsung service","detail":"Request authorised service if the code remains or returns. Dismantle nothing and make no electrical measurements."}],"when_to_call_technician_html":f"<p>Arrange Samsung service if {code} remains or returns after safe external checks. Door locks, switches, fans, valves, wiring and electronics are not user repairs.</p><p>Unplug immediately for leakage near electricity, burning smell, smoke, sparks, abnormal heat or tripped protection.</p>","prevention_html":"<p>Follow load limits and installation instructions, keep the door seal and external controls clean and dry, and inspect visible hoses as the manual specifies.</p><p>Record the complete code and model number. Internal lock, fan, valve and electronics faults cannot be prevented through dismantling.</p>"})
 v["parts_json"]=[]
 assert len(v["title_tag"])<=70 and len(v["meta_description"])<=165
 return v

def main():
 b=json.loads((BASE_DIR/'data/backups/article_reviews/batch-027-samsung-door-water-fan-before.json').read_text(encoding='utf-8')); rows={(r['article_id'],r['locale']):r for r in b['rows']}
 o={"batch":"027-samsung-door-water-fan","status":"proposal_only_not_applied","article_ids":list(ITEMS),"sources":["https://www.samsung.com/in/support/home-appliances/how-to-fix-de-dc-error-in-samsung-washing-machine/","https://www.samsung.com/uk/support/home-appliances/what-do-the-codes-on-my-washing-machine-mean/","https://www.samsung.com/sg/support/home-appliances/what-is-error-code-e1-means-in-samsung-washing-machine/","https://www.samsung.com/pt/support/home-appliances/o-que-significam-os-codigos-de-erro-na-maquina-de-lavar-roupa/"],"translations":{}}
 for i,c in ITEMS.items(): o['translations'][str(i)]={"code":c,"preserve":{"en_slug":rows[(i,'en')]['slug'],"sv_slug":rows[(i,'sv')]['slug']},"en":make(i,False),"sv":make(i,True)}
 p=BASE_DIR/'data/article_reviews/batch-027-samsung-door-water-fan-proposal.json'; p.write_text(json.dumps(o,ensure_ascii=False,indent=2),encoding='utf-8'); print(p)
if __name__=='__main__':main()
