"""Build P1 articles only for remaining codes covered by official Samsung tables."""
from __future__ import annotations
import json
from config.settings import BASE_DIR, supabase
from pipeline import build_p0_batch_041_deterministic as base

SRC={"washing-machines":"https://www.samsung.com/uk/support/home-appliances/what-do-the-codes-on-my-washing-machine-mean/","dishwashers":"https://www.samsung.com/uk/support/home-appliances/displayed-information-codes-on-my-dishwasher/","dryers":"https://www.samsung.com/us/support/troubleshoot/TSG10001006/"}
# id: category, family, concise verified meaning
C={
500:("washing-machines","door","a door-lock condition"),584:("washing-machines","heat","a water-heating condition"),585:("washing-machines","heat","a water-heating condition"),586:("washing-machines","heat","a water-heating condition"),589:("washing-machines","door","a door-lock condition"),590:("washing-machines","door","a door-lock condition"),761:("washing-machines","heat","a water-heating condition"),853:("washing-machines","comm","a communication condition between electronic controls"),859:("washing-machines","heat","a water-heating condition"),870:("washing-machines","voltage","a low-voltage or power-supply condition"),875:("washing-machines","comm","a communication condition between electronic controls"),876:("washing-machines","comm","a communication condition between electronic controls"),878:("washing-machines","foam","excessive detergent foam"),879:("washing-machines","sensor","a MEMS or vibration-sensor condition"),880:("washing-machines","sensor","a MEMS or vibration-sensor condition"),
419:("dishwashers","overflow","an over-level or overflow condition"),422:("dishwashers","level","a low-water-level condition"),432:("dishwashers","zone","a WaterWall reflector or zone-wash condition"),442:("dishwashers","heat","a heater condition"),443:("dishwashers","filter","a clogged-filter condition on applicable models"),444:("dishwashers","leak","a leak or low-water condition, depending on model"),446:("dishwashers","supply","a water-supply condition"),447:("dishwashers","pump","a pump-operation condition"),450:("dishwashers","leak","a leak check"),451:("dishwashers","button","a stuck-button condition"),455:("dishwashers","filter","a clogged-filter condition on applicable models"),457:("dishwashers","supply","a water-supply condition"),458:("dishwashers","supply","a hot-water supply condition"),459:("dishwashers","zone","a WaterWall reflector or zone-wash condition"),461:("dishwashers","overflow","an over-level or overflow condition"),490:("dishwashers","overflow","an over-level or overflow condition"),491:("dishwashers","temp","a temperature-sensor condition"),493:("dishwashers","zone","a WaterWall reflector or zone-wash condition"),494:("dishwashers","zone","a WaterWall reflector or zone-wash condition"),
569:("dryers","button","a stuck-button condition"),570:("dryers","voltage","a power-frequency condition"),571:("dryers","voltage","a voltage or power-supply condition"),572:("dryers","comm","a communication condition between electronic controls"),573:("dryers","comm","a communication condition between electronic controls"),574:("dryers","door","a door-switch or door-closure condition"),597:("dryers","voltage","a voltage or power-supply condition"),
}
ACTIONS={"door":"Remove trapped laundry, close the door firmly and request service if the code returns","heat":"Stop use and request Samsung service if the code returns; do not test internal heaters","comm":"Record the code, power off once and request Samsung service if it returns","voltage":"Check the plug and household circuit from a dry safe position; use no extension lead","foam":"Let foam subside and use the detergent type and dose specified in the model manual","sensor":"Stop, record the complete code and request service if a single safe restart does not clear it","overflow":"Close the water supply, stop use and request service if water remains or the code returns","level":"Open the supply and check visible hoses; request service if the condition remains","zone":"Check that dishes do not obstruct documented moving parts and follow the exact model manual","filter":"Switch off, let hot water cool and clean only the user-accessible filter described by the manual","leak":"Close the water valve, isolate power safely and do not run the dishwasher until assessed","supply":"Open the supply, check household flow and straighten the visible inlet hose","pump":"Switch off and inspect only the user-accessible filter and drain path described by the manual","button":"Release and wipe accessible controls while off; request service if a button remains stuck","temp":"Stop use and request Samsung service if the temperature code returns"}
SV_ACTION="Följ endast säkra yttre kontroller i manualen för exakt modell och boka Samsung-service om koden kvarstår"

def make(aid:int,sv:bool)->dict:
    cat,family,meaning=C[aid]; code=next(r["code"] for r in CURRENT if r["id"]==aid); appliance={"washing-machines":"washing machine","dishwashers":"dishwasher","dryers":"dryer"}[cat]; sva={"washing-machines":"tvättmaskin","dishwashers":"diskmaskin","dryers":"torktumlare"}[cat]; action=ACTIONS[family]
    item={"type":"code","subject":code,"en_title":f"Samsung {appliance.title()} Error {code}","sv_title":f"Samsung-{sva} felkod {code}","en_meaning":f"Samsung identifies {code} as {meaning}","sv_meaning":f"Samsung anger att {code} är ett modellspecifikt {family}-tillstånd enligt den officiella kodtabellen","en_action":action,"sv_action":SV_ACTION,"en_causes":["External operating or installation condition","User-accessible restriction where documented","Model-specific sensor or control condition","Internal fault requiring Samsung service"],"sv_causes":["Yttre drift- eller installationstillstånd","Användaråtkomligt hinder där detta dokumenteras","Modellspecifikt givar- eller styrtillstånd","Internt fel som kräver Samsung-service"]}
    v=base.make(item,sv); v.update({"parts_json":[],"symptoms_json":[],"affected_models_json":[],"translation_status":"pending" if sv else "published","source_locale":"en","translated_by":"hybrid"}); slugap={"washing-machines":"washing-machine","dishwashers":"dishwasher","dryers":"dryer"}[cat] if not sv else {"washing-machines":"tvattmaskin","dishwashers":"diskmaskin","dryers":"torktumlare"}[cat]; v["slug"]=f'samsung-{slugap}-{"felkod" if sv else "error-code"}-{code.lower().replace("/","-").replace("(","").replace(")","")}'; return v

CURRENT=supabase.table("error_codes").select("id,code").in_("id",list(C)).execute().data or []
def main()->None:
    out={"batch":"p1-verified-remaining","error_code_ids":list(C),"sources":SRC,"entries":{}}
    for aid,(cat,_,_) in C.items():
        code=next(r["code"] for r in CURRENT if r["id"]==aid); out["entries"][str(aid)]={"brand":"samsung","category":cat,"code":code,"classification":"A","source":SRC[cat],"uncertainties":["Exact behaviour varies by model; exact model manual controls"],"en":make(aid,False),"sv":make(aid,True)}
    p=BASE_DIR/"data/article_reviews/p1-verified-remaining-proposal.json"; p.write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding="utf-8"); print(p)
if __name__=="__main__": main()
