"""Build reviewed Siemens E16/E18/E20/E21/E23 content."""
from __future__ import annotations
import json
from config.settings import BASE_DIR
from pipeline.build_p0_batch_002_deterministic import build_en,build_sv

ITEMS={208:"E16",210:"E18",211:"E20",212:"E21",214:"E23"}
DATA={
208:("Siemens identifies E16 or F16 as a door that is not locked properly; laundry may be trapped","Siemens anger att E16 eller F16 betyder att luckan inte är ordentligt låst; tvätt kan ha fastnat","Remove trapped laundry and close the door firmly without forcing it; reduce the load if needed","Ta bort tvätt som fastnat och stäng luckan ordentligt utan att tvinga den; minska lasten vid behov","door"),
210:("Siemens identifies E18 or F18 as a blocked filter or a blocked or kinked drain hose","Siemens anger att E18 eller F18 betyder blockerat filter eller blockerad eller vikt avloppsslang","Close the water tap, switch off and unplug, let hot water cool, then check the hose and clean the user-accessible filter exactly as the manual specifies","Stäng vattenkranen, stäng av och dra ur kontakten, låt hett vatten svalna och kontrollera sedan slangen och rengör det användaråtkomliga filtret exakt enligt manualen","drain"),
211:("Siemens identifies E20 or F20 as unexpected heating","Siemens anger att E20 eller F20 betyder oväntad uppvärmning","Switch the washer off once and arrange Siemens service if E20 remains or returns; do not test the heater or sensor","Stäng av tvättmaskinen en gång och boka Siemens-service om E20 kvarstår eller återkommer; testa inte värmare eller sensor","heat"),
212:("E21 is not defined in Siemens' generic public washer error table; confirm the complete code and exact E-Nr manual before assigning a meaning","E21 definieras inte i Siemens generella offentliga felkodstabell för tvättmaskiner; bekräfta hela koden och manualen för exakt E‑Nr innan betydelse anges","Photograph the complete display and contact Siemens with the exact E-Nr; do not dismantle or measure internal parts","Fotografera hela displayen och kontakta Siemens med exakt E‑Nr; demontera eller mät inga interna delar","unknown"),
214:("Siemens identifies E23 as leakage or water in the washer base","Siemens anger att E23 betyder läckage eller vatten i tvättmaskinens botten","Close the water tap immediately, stop using the washer and isolate power only from a safe, dry location","Stäng vattenkranen omedelbart, sluta använda maskinen och bryt strömmen endast från en säker och torr plats","leak"),
}
CAUSES={
"door":(["Door not fully closed","Laundry trapped at the door","Load prevents locking","Door-lock or control fault"],["Luckan är inte helt stängd","Tvätt har fastnat vid luckan","Lasten hindrar låsning","Fel i lucklås eller styrning"]),
"drain":(["Kinked or blocked drain hose","Blocked user-accessible filter","Blocked household waste connection","Internal pump or control fault"],["Vikt eller blockerad avloppsslang","Blockerat användaråtkomligt filter","Blockerad avloppsanslutning i bostaden","Internt pump- eller styrfel"]),
"heat":(["Unexpected heating condition","Temperature signal outside expected range","Internal heater or sensor fault","Wiring or control-electronics fault"],["Oväntat uppvärmningstillstånd","Temperatursignal utanför förväntat område","Internt värmar- eller sensorfel","Fel i kablage eller styrelektronik"]),
"unknown":(["Incomplete or misread display","Model-specific information code","A neighbouring character is not visible","Internal condition requiring Siemens diagnosis"],["Ofullständig eller feltolkad display","Modellspecifik informationskod","Ett intilliggande tecken syns inte","Internt tillstånd som kräver Siemens-diagnos"]),
"leak":(["External hose or connection leak","Door seal or detergent-related leakage","Drainage or overflow condition","Internal hose, valve, tub or pump fault"],["Läckage från yttre slang eller anslutning","Lucktätning eller tvättmedelsrelaterat läckage","Tömnings- eller överfyllnadstillstånd","Internt fel i slang, ventil, behållare eller pump"]),
}

def brand(v):
 return json.loads(json.dumps(v,ensure_ascii=False).replace('Bosch','Siemens').replace('bosch','Siemens'))

def make(i,sv):
 code=ITEMS[i];me,ms,ae,av,kind=DATA[i];meaning=ms if sv else me;action=av if sv else ae;v=brand(build_sv(code,meaning,action) if sv else build_en(code,meaning,action));causes=CAUSES[kind][1 if sv else 0]
 if sv:v.update({"title_tag":f"Siemens-tvättmaskin felkod {code}: säkra steg","meta_description":f"Visar Siemens-tvättmaskinen {code}? Läs verifierad betydelse, säkra yttre kontroller och när Siemens-service krävs.","h1":f"Vad betyder {code} på en Siemens-tvättmaskin?","description":meaning[0].upper()+meaning[1:]+".","quick_fix":action+" (cirka 5–30 minuter).","intro_html":f"<p>{meaning[0].upper()+meaning[1:]}.</p><p>{action}. Öppna inga paneler, gör inga elektriska mätningar och beställ inte reservdel från koden ensam.</p>","causes_json":[{"cause":x,"detail":"Detta är en möjlig orsak; exakt E‑Nr-manual och professionell diagnos avgör interna fel."} for x in causes],"steps_json":[{"step":1,"action":"Stoppa säkert","detail":"Stoppa programmet, vänta tills trumman står stilla och tvinga inte luckan."},{"step":2,"action":"Dokumentera kod och E‑Nr","detail":f"Fotografera hela {code}-visningen och anteckna E‑Nr, programfas och synliga symptom."},{"step":3,"action":"Gör endast rätt yttre kontroll","detail":action+". Följ manualen för exakt E‑Nr vid tömning eller filterrengöring."},{"step":4,"action":"Testa högst en gång","detail":"Testa endast efter korrigerad yttre orsak och aldrig vid läckage, bränd lukt, rök, onormal värme eller elskada."},{"step":5,"action":"Boka Siemens-service","detail":"Boka service om koden kvarstår eller återkommer. Demontera inget och mät inga interna delar."}],"when_to_call_technician_html":f"<p>Boka Siemens-service om {code} kvarstår efter säkra kontroller. Vid E23 ska kranen stängas omedelbart och maskinen inte användas.</p><p>Lucklås, värmare, sensorer, pumpar, ventiler, kablage och elektronik är inte användarreparationer.</p>","prevention_html":"<p>Följ installations-, last- och doseringsanvisningar och håll synliga slangar och användaråtkomliga filter rena enligt manualen.</p><p>Interna mekaniska och elektriska fel kan inte förebyggas genom demontering.</p>"})
 else:v.update({"title_tag":f"Siemens Washing Machine Error {code}: Safe Steps","meta_description":f"Siemens washer showing {code}? Read the verified meaning, safe external checks and when Siemens service is required.","h1":f"What Does {code} Mean on a Siemens Washing Machine?","description":meaning[0].upper()+meaning[1:]+".","quick_fix":action+" (about 5–30 minutes).","intro_html":f"<p>{meaning[0].upper()+meaning[1:]}.</p><p>{action}. Open no panels, make no electrical measurements and do not order a part from the code alone.</p>","causes_json":[{"cause":x,"detail":"This is a possible cause; the exact E-Nr manual and professional diagnosis determine internal faults."} for x in causes],"steps_json":[{"step":1,"action":"Stop safely","detail":"Stop the programme, wait for the drum to stop and do not force the door."},{"step":2,"action":"Record the code and E-Nr","detail":f"Photograph the complete {code} display and note the E-Nr, programme stage and visible symptoms."},{"step":3,"action":"Make only the correct external check","detail":action+". Follow the exact E-Nr manual when draining water or cleaning a filter."},{"step":4,"action":"Test no more than once","detail":"Test only after correcting an external cause, and never with leakage, burning smell, smoke, abnormal heat or electrical damage."},{"step":5,"action":"Arrange Siemens service","detail":"Request service if the code remains or returns. Dismantle nothing and measure no internal parts."}],"when_to_call_technician_html":f"<p>Arrange Siemens service if {code} remains after safe checks. For E23, close the tap immediately and do not use the washer.</p><p>Door locks, heaters, sensors, pumps, valves, wiring and electronics are not user repairs.</p>","prevention_html":"<p>Follow installation, load and detergent instructions and keep visible hoses and user-accessible filters clean as the manual specifies.</p><p>Internal mechanical and electrical faults cannot be prevented through dismantling.</p>"})
 v['parts_json']=[];assert len(v['title_tag'])<=70 and len(v['meta_description'])<=165;return v

def main():
 b=json.loads((BASE_DIR/'data/backups/article_reviews/batch-031-siemens-e16-e23-before.json').read_text(encoding='utf-8'));rows={(r['article_id'],r['locale']):r for r in b['rows']};o={"batch":"031-siemens-e16-e23","status":"proposal_only_not_applied","article_ids":list(ITEMS),"sources":["https://www.siemens-home.bsh-group.com/ae/customer-service/support/troubleshooting/washing-machines/error-codes-symbols","https://www.siemens-home.bsh-group.com/ae/customer-service/support/troubleshooting/washing-machines/error-codes-e18-f18","https://www.siemens-home.bsh-group.com/uk/customer-service/support/washing-machine"],"translations":{}}
 for i,c in ITEMS.items():o['translations'][str(i)]={"code":c,"preserve":{"en_slug":rows[(i,'en')]['slug'],"sv_slug":rows[(i,'sv')]['slug']},"en":make(i,False),"sv":make(i,True)}
 p=BASE_DIR/'data/article_reviews/batch-031-siemens-e16-e23-proposal.json';p.write_text(json.dumps(o,ensure_ascii=False,indent=2),encoding='utf-8');print(p)
if __name__=='__main__':main()
