"""Build canonical library and Samsung dishwasher/dryer P2 pilot proposal."""
from __future__ import annotations
import json
from config.settings import BASE_DIR
from pipeline import build_p0_batch_041_deterministic as base

LIB={
"dishwashers":[("not-draining","Dishwasher Not Draining","Diskmaskinen tömmer inte",[420]),("not-filling","Dishwasher Not Filling With Water","Diskmaskinen fyller inte med vatten",[556,446,457,458]),("not-starting","Dishwasher Not Starting","Diskmaskinen startar inte",[]),("not-cleaning","Dishwasher Not Cleaning Dishes","Diskmaskinen diskar inte rent",[443,455]),("not-drying","Dishwasher Not Drying Dishes","Diskmaskinen torkar inte disken",[442]),("leaking","Dishwasher Leaking Water","Diskmaskinen läcker vatten",[523,450,444]),("unusual-noise","Dishwasher Making Unusual Noise","Diskmaskinen låter ovanligt",[]),("door-not-closing","Dishwasher Door Not Closing","Diskmaskinens lucka stängs inte",[]),("stopping-mid-cycle","Dishwasher Stopping Mid-Cycle","Diskmaskinen stannar mitt i programmet",[]),("bad-smell","Dishwasher Has a Bad Smell","Diskmaskinen luktar illa",[])],
"dryers":[("not-heating","Dryer Not Heating","Torktumlaren blir inte varm",[567]),("not-starting","Dryer Not Starting","Torktumlaren startar inte",[571,597]),("not-spinning","Dryer Not Spinning","Torktumlaren roterar inte",[]),("clothes-remain-wet","Clothes Remain Wet","Kläderna förblir våta",[]),("taking-too-long","Dryer Taking Too Long","Torktumlaren tar för lång tid",[]),("stopping-mid-cycle","Dryer Stopping Mid-Cycle","Torktumlaren stannar mitt i programmet",[572,573]),("overheating","Dryer Overheating","Torktumlaren överhettas",[567]),("unusual-noise","Dryer Making Unusual Noise","Torktumlaren låter ovanligt",[]),("drum-not-turning","Dryer Drum Not Turning","Torktumlarens trumma roterar inte",[]),("door-not-closing","Dryer Door Not Closing","Torktumlarens lucka stängs inte",[568,574])]
}
SRC={"dishwashers":["https://www.samsung.com/us/home-appliances/faq/faq-dishwasher/","https://www.samsung.com/us/support/troubleshooting/TSG01001363/","https://www.samsung.com/us/support/troubleshoot/TSG10010593/"],"dryers":["https://www.samsung.com/us/home-appliances/faq/faq-dryer/","https://www.samsung.com/us/support/troubleshoot/TSG10001001/","https://www.samsung.com/us/support/troubleshoot/TSG10000730/"]}

def article(cat:str,slug:str,en_name:str,sv_name:str,sv:bool)->dict:
    appliance="dishwasher" if cat=="dishwashers" else "dryer"; sva="diskmaskin" if cat=="dishwashers" else "torktumlare"
    item={"type":"fault","subject":slug,"en_title":f"Samsung {en_name}","sv_title":f"Samsung: {sv_name}","en_meaning":f"The Samsung {appliance} shows the observed symptom: {en_name.lower()}","sv_meaning":f"Samsung-{sva}en visar det observerade symtomet: {sv_name.lower()}","en_action":"Stop safely, check installation and user-accessible cleaning points, then follow the exact model manual","sv_action":"Stoppa säkert, kontrollera installation och användaråtkomliga rengöringspunkter och följ sedan exakt modellmanual","en_causes":["Installation or operating condition","Loading, cycle or user setting","Blocked user-accessible filter, hose or airflow path","Internal sensor, control or mechanical fault"],"sv_causes":["Installations- eller driftstillstånd","Lastning, program eller användarinställning","Blockerat användaråtkomligt filter, slang eller luftflöde","Internt givar-, styr- eller mekanikfel"]}
    v=base.make(item,sv); v.update({"parts_json":[],"symptoms_json":[],"affected_models_json":[],"slug":f'samsung-{sva if sv else appliance}-{slug}'.replace("ä","a").replace("ö","o"),"translation_status":"pending" if sv else "published","source_locale":"en","translated_by":"hybrid"}); return v

def main()->None:
    canonical={cat:[{"slug":s,"canonical_name":en,"sv_name":sv} for s,en,sv,_ in rows] for cat,rows in LIB.items()}; (BASE_DIR/"data/p2-canonical-symptom-library.json").write_text(json.dumps(canonical,ensure_ascii=False,indent=2),encoding="utf-8")
    out={"batch":"p2-samsung-pilot-clusters","brand":"samsung","sources":SRC,"clusters":[]}
    for cat,rows in LIB.items():
        for slug,en,sv,maps in rows: out["clusters"].append({"category":cat,"slug":slug,"canonical_name":en,"severity":"medium","has_error_code":bool(maps),"fault_translations":{"en":{"symptom_name":en,"meta_title":f"Samsung {en}","meta_description":f"Troubleshoot a Samsung {en.lower()} with safe checks, likely causes and clear guidance on when service is required."},"sv":{"symptom_name":sv,"meta_title":f"Samsung: {sv}","meta_description":f"Felsök när {sv.lower()} med säkra kontroller, troliga orsaker och tydliga råd om när service krävs."}},"article":{"en":article(cat,slug,en,sv,False),"sv":article(cat,slug,en,sv,True)},"mappings":[{"error_code_id":i,"reason":"Official Samsung code meaning can produce this observed symptom","source":SRC[cat][0],"confidence":"high","status":"approved"} for i in maps]})
    p=BASE_DIR/"data/article_reviews/p2-samsung-pilot-clusters-proposal.json"; p.write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding="utf-8"); print(p)
if __name__=="__main__": main()
