"""Build reviewed Samsung leak/fill/door/heat/vibration fault content."""
from __future__ import annotations
import json
from config.settings import BASE_DIR
from pipeline.build_p0_batch_002_deterministic import build_en,build_sv

ITEMS={
132:{"key":"leak","en":"is leaking water","sv":"läcker vatten","h1e":"Samsung Washing Machine Leaking Water: Safe Checks","h1s":"Samsung-tvättmaskinen läcker vatten: säkra kontroller"},
133:{"key":"fill","en":"won't fill with water","sv":"fyller inte med vatten","h1e":"Samsung Washing Machine Won't Fill: Safe Checks","h1s":"Samsung-tvättmaskinen fyller inte: säkra kontroller"},
134:{"key":"door","en":"door won't open","sv":"lucka öppnas inte","h1e":"Samsung Washing Machine Door Won't Open: Safe Steps","h1s":"Samsung-tvättmaskinens lucka öppnas inte: säkra steg"},
136:{"key":"heat","en":"is not heating water","sv":"värmer inte vattnet","h1e":"Samsung Washing Machine Not Heating: Safe Checks","h1s":"Samsung-tvättmaskinen värmer inte: säkra kontroller"},
137:{"key":"vibration","en":"is vibrating excessively","sv":"vibrerar för mycket","h1e":"Samsung Washing Machine Vibrating: Safe Checks","h1s":"Samsung-tvättmaskinen vibrerar: säkra kontroller"},
}
DATA={
"leak":("A Samsung washer can leak because of a hose or connection, trapped material at the door seal, excess detergent, incorrect drainage or an internal fault","En Samsung-tvättmaskin kan läcka på grund av slang eller anslutning, material vid lucktätningen, för mycket tvättmedel, felaktig tömning eller ett internt fel","Stop the cycle, close the water taps and isolate power only if the plug and surrounding area are dry; do not use the washer until the leak source is resolved","Stoppa programmet, stäng vattenkranarna och bryt strömmen endast om kontakten och området är torra; använd inte maskinen innan läckans orsak är löst"),
"fill":("A Samsung washer may not fill because the tap is closed, flow is insufficient, a hose is kinked, the mesh filter is blocked or the drain hose is installed incorrectly","En Samsung-tvättmaskin kan utebli från att fylla på grund av stängd kran, otillräckligt flöde, vikt slang, blockerat nätfilter eller felmonterad avloppsslang","Open the taps fully, confirm household flow and straighten visible hoses; clean the inlet mesh only as the exact model manual specifies","Öppna kranarna helt, kontrollera vattenflödet och räta synliga slangar; rengör inloppsnätet endast enligt manualen för exakt modell"),
"door":("Samsung keeps the door locked while water is present, the drum or appliance is hot, a cycle is active or Child Lock is enabled; a persistent lock may require service","Samsung håller luckan låst när vatten finns kvar, trumman eller maskinen är varm, ett program pågår eller barnlåset är aktivt; ett kvarstående lås kan kräva service","Do not force the door; wait for the cycle and cooling period, verify Child Lock and drain water only with the exact model's user procedure","Tvinga inte luckan; vänta tills programmet och avsvalningen är klara, kontrollera barnlåset och töm vatten endast enligt användarinstruktionen för exakt modell"),
"heat":("Apparent lack of heating can depend on cycle design, inlet temperature or household hot-water supply; a displayed heater or temperature code requires Samsung diagnosis","Upplevd utebliven uppvärmning kan bero på programutformning, inloppstemperatur eller bostadens varmvattenförsörjning; en visad värmar- eller temperaturkod kräver Samsung-diagnos","Confirm the selected cycle and external hot-water supply where applicable, record any code and arrange service if heating remains abnormal","Kontrollera valt program och extern varmvattenförsörjning där det är relevant, dokumentera eventuell kod och boka service om uppvärmningen förblir onormal"),
"vibration":("Samsung identifies an unstable or unlevel installation, shipping bolts and an unbalanced or unsuitable load as common causes of excessive vibration","Samsung anger instabil eller ojämn installation, transportbultar och obalanserad eller olämplig last som vanliga orsaker till kraftiga vibrationer","Stop the cycle, redistribute the load and verify that the washer stands firm and level; for a new front loader, confirm shipping-bolt removal using the installation manual","Stoppa programmet, fördela lasten och kontrollera att maskinen står stadigt och plant; på en ny frontmatad maskin bekräftar du borttagna transportbultar enligt installationsmanualen"),
}
CAUSES={
"leak":(["Damaged or loose external hose connection","Debris or damage at the door seal","Excess detergent or incorrect drain installation","Internal hose, valve, tub or pump fault"],["Skadad eller lös yttre slanganslutning","Smuts eller skada vid lucktätningen","För mycket tvättmedel eller felmonterat avlopp","Internt fel i slang, ventil, behållare eller pump"]),
"fill":(["Closed tap or household water outage","Low pressure or kinked inlet hose","Blocked user-cleanable inlet mesh","Incorrect drain installation or internal inlet fault"],["Stängd kran eller vattenavbrott","Lågt tryck eller vikt tilloppsslang","Blockerat användarrengörbart inloppsnät","Felaktig avloppsinstallation eller internt inloppsfel"]),
"door":(["Cycle, water or heat safety lock","Child Lock is enabled","Water has not drained","Door-lock or control fault"],["Säkerhetslås på grund av program, vatten eller värme","Barnlåset är aktiverat","Vattnet har inte tömts","Fel i lucklås eller styrning"]),
"heat":(["Cycle uses limited or no heating","External hot-water supply is unavailable on applicable models","Temperature information code","Internal heater, sensor, wiring or control fault"],["Programmet använder begränsad eller ingen uppvärmning","Extern varmvattenförsörjning saknas på berörda modeller","Informationskod för temperatur","Internt fel i värmare, sensor, kablage eller styrning"]),
"vibration":(["Unbalanced, single-heavy-item or overloaded load","Washer is not level on a solid floor","Shipping bolts remain on a front loader","Internal suspension, bearing or drive fault"],["Obalanserad, ensam tung eller för stor last","Maskinen står inte plant på fast golv","Transportbultar sitter kvar på en frontmatad maskin","Internt fel i upphängning, lager eller drivning"]),
}

def faq(item,action,sv):
 subject=item['sv'] if sv else item['en']
 if sv:return [{"question":f"Kan jag använda maskinen när den {subject}?","answer":action+". Fortsätt inte om problemet kvarstår eller om det finns vatten nära el, bränd lukt, rök eller onormal värme."},{"question":"Vilka kontroller är säkra för användaren?","answer":"Kontrollera endast synliga slangar, kranar, last, nivå, program och användaråtkomliga delar som exakt modellmanual beskriver."},{"question":"Ska jag tvinga luckan eller öppna en panel?","answer":"Nej. Tvinga aldrig luckan, flytta inte en vattenfylld maskin och ta inte bort några höljen."},{"question":"Visar symtomet vilken reservdel som behövs?","answer":"Nej. Samsung eller en kvalificerad tekniker måste diagnostisera interna komponenter före beställning."},{"question":"När krävs service?","answer":"Boka service om säkra yttre kontroller inte räcker eller om problemet återkommer."}]
 return [{"question":f"Can I use the washer when it {subject}?","answer":action+". Do not continue if the problem remains or there is water near electricity, burning smell, smoke or abnormal heat."},{"question":"Which checks are safe for the user?","answer":"Check only visible hoses, taps, load, level, programme and user-accessible items described by the exact model manual."},{"question":"Should I force the door or open a panel?","answer":"No. Never force the door, move a water-filled washer or remove any enclosure."},{"question":"Does the symptom identify a replacement part?","answer":"No. Samsung or a qualified technician must diagnose internal components before ordering."},{"question":"When is service required?","answer":"Arrange service when safe external checks do not resolve the problem or it returns."}]

def make(i,sv):
 item=ITEMS[i];kind=item['key'];me,ms,ae,av=DATA[kind];meaning=ms if sv else me;action=av if sv else ae;v=build_sv(item['sv'],meaning,action) if sv else build_en(item['en'],meaning,action);causes=CAUSES[kind][1 if sv else 0];h1=item['h1s' if sv else 'h1e']
 common_causes=[{"cause":x,"detail":("Detta är en möjlig orsak; exakt modellmanual och professionell diagnos avgör interna fel." if sv else "This is a possible cause; the exact model manual and professional diagnosis determine internal faults.")} for x in causes]
 if sv:v.update({"title_tag":h1,"meta_description":f"Samsung-tvättmaskinen {item['sv']}? Läs säkra yttre kontroller, viktiga stoppregler och när auktoriserad service krävs.","h1":h1,"description":meaning[0].upper()+meaning[1:]+".","quick_fix":action+" (cirka 5–30 minuter).","intro_html":f"<p>{meaning[0].upper()+meaning[1:]}.</p><p>{action}. Öppna inga paneler, gör inga elektriska mätningar och beställ inte reservdel från symtomet ensam.</p>","causes_json":common_causes,"steps_json":[{"step":1,"action":"Stoppa säkert","detail":"Stoppa programmet och vänta tills trumman står stilla. Vid vatten nära el bryter du strömmen på säkert avstånd."},{"step":2,"action":"Dokumentera","detail":"Fotografera display och synliga symptom och anteckna modellnummer och programfas."},{"step":3,"action":"Kontrollera endast yttre förhållanden","detail":action+". Följ alltid manualen för exakt modell."},{"step":4,"action":"Testa högst en gång","detail":"Testa endast efter korrigerad yttre orsak och aldrig vid läckage, bränd lukt, rök, onormal värme eller elskada."},{"step":5,"action":"Boka Samsung-service","detail":"Boka service om problemet kvarstår eller återkommer. Demontera inget och mät inga interna delar."}],"when_to_call_technician_html":"<p>Boka Samsung-service om säkra yttre kontroller inte räcker. Lås, värmare, sensorer, ventiler, pumpar, upphängning, kablage och elektronik är inte användarreparationer.</p><p>Avbryt direkt vid vatten nära el, bränd lukt, rök, gnistor, onormal värme eller utlöst elskydd.</p>","prevention_html":"<p>Följ installations-, last- och doseringsanvisningar, håll synliga slangar och tätningar rena och kontrollera att maskinen står plant.</p><p>Interna mekaniska och elektriska fel kan inte förebyggas genom demontering.</p>","faq_json":faq(item,action,True)})
 else:v.update({"title_tag":h1,"meta_description":f"Samsung washer {item['en']}? Read safe external checks, important stop rules and when authorised service is required.","h1":h1,"description":meaning[0].upper()+meaning[1:]+".","quick_fix":action+" (about 5–30 minutes).","intro_html":f"<p>{meaning[0].upper()+meaning[1:]}.</p><p>{action}. Open no panels, make no electrical measurements and do not order a part from the symptom alone.</p>","causes_json":common_causes,"steps_json":[{"step":1,"action":"Stop safely","detail":"Stop the programme and wait for the drum to stop. If water is near electricity, isolate power from a safe, dry location."},{"step":2,"action":"Record the symptom","detail":"Photograph the display and visible symptoms and note the model number and programme stage."},{"step":3,"action":"Check only external conditions","detail":action+". Always follow the exact model manual."},{"step":4,"action":"Test no more than once","detail":"Test only after correcting an external cause, and never with leakage, burning smell, smoke, abnormal heat or electrical damage."},{"step":5,"action":"Arrange Samsung service","detail":"Request service if the problem remains or returns. Dismantle nothing and measure no internal parts."}],"when_to_call_technician_html":"<p>Arrange Samsung service when safe external checks do not resolve the problem. Locks, heaters, sensors, valves, pumps, suspension, wiring and electronics are not user repairs.</p><p>Stop immediately for water near electricity, burning smell, smoke, sparks, abnormal heat or tripped protection.</p>","prevention_html":"<p>Follow installation, load and detergent instructions, keep visible hoses and seals clean, and make sure the washer is level.</p><p>Internal mechanical and electrical faults cannot be prevented through dismantling.</p>","faq_json":faq(item,action,False)})
 v['parts_json']=[];assert len(v['title_tag'])<=70 and len(v['meta_description'])<=165;return v

def main():
 b=json.loads((BASE_DIR/'data/backups/article_reviews/batch-029-samsung-water-door-heat-vibration-before.json').read_text(encoding='utf-8'));rows={(r['article_id'],r['locale']):r for r in b['rows']};o={"batch":"029-samsung-water-door-heat-vibration","status":"proposal_only_not_applied","article_ids":list(ITEMS),"sources":["https://www.samsung.com/us/support/troubleshoot/TSG10001007/","https://www.samsung.com/us/support/troubleshoot/TSG10007295/","https://www.samsung.com/in/support/home-appliances/samsung-front-load-washing-machine-how-to-unlock-the-door/","https://www.samsung.com/us/support/troubleshoot/TSG10000997/","https://www.samsung.com/us/support/troubleshoot/TSG10007111/"],"translations":{}}
 for i,item in ITEMS.items():o['translations'][str(i)]={"code":item['en'],"preserve":{"en_slug":rows[(i,'en')]['slug'],"sv_slug":rows[(i,'sv')]['slug']},"en":make(i,False),"sv":make(i,True)}
 p=BASE_DIR/'data/article_reviews/batch-029-samsung-water-door-heat-vibration-proposal.json';p.write_text(json.dumps(o,ensure_ascii=False,indent=2),encoding='utf-8');print(p)
if __name__=='__main__':main()
