"""Build reviewed Samsung OE/SF1/tE and no-drain/no-spin content."""
from __future__ import annotations
import json
from config.settings import BASE_DIR
from pipeline.build_p0_batch_002_deterministic import build_en,build_sv

ITEMS={49:("OE","overflow"),50:("SF1","system"),51:("tE","temperature"),129:("won't drain","drain"),130:("won't spin","spin")}

DATA={
"overflow":("Samsung identifies OE or OF as an overflow condition","Samsung anger att OE eller OF är ett överfyllnadstillstånd","Stop the cycle, turn off the water tap and power, and do not run another cycle if water continues entering or leaks","Stoppa programmet, stäng vattenkranen och strömmen och kör inte ett nytt program om vatten fortsätter att fyllas på eller läcker"),
"system":("Samsung identifies SF1 as a system error that requires model-specific diagnosis","Samsung anger att SF1 är ett systemfel som kräver modellspecifik diagnos","Switch the washer off for two to three minutes once; arrange Samsung service if SF1 returns","Stäng av tvättmaskinen i två till tre minuter en gång; boka Samsung-service om SF1 återkommer"),
"temperature":("Samsung identifies tE as a temperature-sensor error","Samsung anger att tE är ett fel i temperatursensorn","Stop the washer and contact Samsung service; do not test the sensor, heater, wiring or control board","Stoppa tvättmaskinen och kontakta Samsung-service; testa inte sensor, värmare, kablage eller styrkort"),
"drain":("A Samsung washer that will not drain commonly has a kinked drain hose, incorrect installation or a blocked user-accessible pump filter","En Samsung-tvättmaskin som inte tömmer har ofta en vikt avloppsslang, felaktig installation eller ett blockerat användaråtkomligt pumpfilter","Let hot water cool, unplug the washer, check the external drain hose and clean the pump filter only if the exact manual provides a user procedure","Låt hett vatten svalna, dra ur kontakten, kontrollera den yttre avloppsslangen och rengör pumpfiltret endast om exakt manual har en användarinstruktion"),
"spin":("A Samsung washer may not spin because the load is unbalanced, it cannot drain, the installation is unstable or service is required","En Samsung-tvättmaskin kan avstå från centrifugering på grund av obalans, utebliven tömning, instabil installation eller ett fel som kräver service","Redistribute the load, verify that the washer is level and check the external drain path before trying one spin cycle","Fördela tvätten jämnt, kontrollera att maskinen står plant och kontrollera den yttre avloppsvägen innan ett centrifugeringsförsök"),
}
CAUSES={
"overflow":(["Excess detergent or foam","Restricted drain path","Incorrect drain-hose installation","Internal inlet valve, level sensor or control fault"],["För mycket tvättmedel eller skum","Begränsad avloppsväg","Felaktig installation av avloppsslangen","Internt fel i inloppsventil, nivåsensor eller styrning"]),
"system":(["Temporary control condition","Model-specific system condition","Internal connection or signal fault","Control-electronics fault"],["Tillfälligt styrtillstånd","Modellspecifikt systemtillstånd","Internt anslutnings- eller signalfel","Fel i styrelektroniken"]),
"temperature":(["Temperature signal outside the expected range","Model-specific temperature sensor fault","Internal wiring fault","Heater or control-electronics fault"],["Temperatursignal utanför förväntat område","Modellspecifikt fel i temperatursensorn","Internt kablagefel","Fel i värmare eller styrelektronik"]),
"drain":(["Kinked or incorrectly installed drain hose","Blocked user-accessible pump filter","Blocked household waste connection","Internal pump or control fault"],["Vikt eller felmonterad avloppsslang","Blockerat användaråtkomligt pumpfilter","Blockerad avloppsanslutning i bostaden","Internt pump- eller styrfel"]),
"spin":(["Unbalanced or unsuitable load","Water has not drained","Washer is not level or stable","Motor, sensor or control fault"],["Obalanserad eller olämplig last","Vattnet har inte tömts","Maskinen står inte plant eller stabilt","Fel i motor, sensor eller styrning"]),
}

def faqs(label,action,sv,fault):
 if sv:return [{"question":f"Kan jag fortsätta använda maskinen när {label} visas?" if not fault else f"Kan jag använda maskinen när den {label}?","answer":action+". Kör inte vidare om problemet kvarstår eller om det finns läckage, bränd lukt, rök eller onormal värme."},{"question":"Är en avstängning en reparation?","answer":"Nej. En enda omstart kan kontrollera ett tillfälligt tillstånd men bevisar inte att ett återkommande fel är löst."},{"question":"Visar symtomet vilken reservdel som ska bytas?","answer":"Nej. Samsung eller en kvalificerad tekniker måste diagnostisera interna delar innan något beställs."},{"question":"Varför behövs modellnumret?","answer":"Kodbetydelser, filteråtkomst och säkra användarsteg kan skilja mellan Samsung-modeller och marknader."},{"question":"Får jag mäta interna delar själv?","answer":"Nej. Ta inte bort paneler och mät inte sensorer, motorer, värmare, pumpar, ventiler, kablage eller elektronik."}]
 return [{"question":f"Can I keep using the washer when {label} appears?" if not fault else f"Can I use the washer when it {label}?","answer":action+". Do not continue if the problem remains or there is leakage, burning smell, smoke or abnormal heat."},{"question":"Is switching off a repair?","answer":"No. One restart may check a temporary condition but does not prove that a recurring fault is repaired."},{"question":"Does the symptom identify a replacement part?","answer":"No. Samsung or a qualified technician must diagnose internal parts before anything is ordered."},{"question":"Why is the model number required?","answer":"Code meanings, filter access and safe user steps can differ between Samsung models and markets."},{"question":"May I measure internal parts myself?","answer":"No. Do not remove panels or measure sensors, motors, heaters, pumps, valves, wiring or electronics."}]

def make(i,sv):
 label,kind=ITEMS[i];me,ms,ae,av=DATA[kind];meaning=ms if sv else me;action=av if sv else ae;fault=kind in ('drain','spin')
 v=build_sv(label,meaning,action) if sv else build_en(label,meaning,action);causes=CAUSES[kind][1 if sv else 0]
 if sv:
  h1=("Samsung-tvättmaskinen tömmer inte: säkra kontroller" if kind=='drain' else "Samsung-tvättmaskinen centrifugerar inte: säkra kontroller") if fault else f"Vad betyder {label} på en Samsung-tvättmaskin?"
  v.update({"title_tag":h1,"meta_description":(("Samsung-tvättmaskinen tömmer inte? Kontrollera slang och användaråtkomligt filter säkert och se när service krävs." if kind=='drain' else "Samsung-tvättmaskinen centrifugerar inte? Kontrollera last, nivå och tömning säkert och se när service krävs.") if fault else f"Visar Samsung-tvättmaskinen {label}? Läs verifierad betydelse, säkra kontroller och när auktoriserad service krävs."),"h1":h1,"description":meaning[0].upper()+meaning[1:]+".","quick_fix":action+" (cirka 5–30 minuter).","intro_html":f"<p>{meaning[0].upper()+meaning[1:]}.</p><p>{action}. Öppna inga paneler, mät inga interna delar och beställ inte en reservdel från symtomet ensam.</p>","causes_json":[{"cause":x,"detail":"Detta är en möjlig orsak; exakt modellmanual och professionell diagnos avgör interna fel."} for x in causes],"steps_json":[{"step":1,"action":"Stoppa säkert","detail":"Stoppa programmet, vänta tills trumman står stilla och tvinga inte luckan."},{"step":2,"action":"Dokumentera","detail":"Fotografera displayen och anteckna modellnummer, programfas och synliga symptom."},{"step":3,"action":"Gör säkra yttre kontroller","detail":action+". Följ exakt manual vid tömning av vatten eller rengöring av filter."},{"step":4,"action":"Testa en gång","detail":"Testa endast efter korrigerad yttre orsak och aldrig vid läckage, bränd lukt, rök, onormal värme eller elskada."},{"step":5,"action":"Boka Samsung-service","detail":"Boka service om felet kvarstår eller återkommer. Demontera inget och gör inga elektriska mätningar."}],"when_to_call_technician_html":"<p>Boka Samsung-service om problemet kvarstår efter säkra yttre kontroller. Sensorer, motorer, fläktar, pumpar, ventiler, kablage och elektronik är inte användarreparationer.</p><p>Koppla ur direkt vid läckage nära el, bränd lukt, rök, gnistor, onormal värme eller utlöst elskydd.</p>","prevention_html":"<p>Följ last- och doseringsanvisningar, håll maskinen plan och kontrollera synliga slangar och användaråtkomliga filter enligt exakt manual.</p><p>Interna sensor-, motor-, pump-, fläkt-, ventil- och elektronikfel kan inte förebyggas genom demontering.</p>","faq_json":faqs("inte tömmer" if kind=='drain' else "inte centrifugerar" if kind=='spin' else label,action,True,fault)})
 else:
  h1=("Samsung Washing Machine Won't Drain: Safe Checks" if kind=='drain' else "Samsung Washing Machine Won't Spin: Safe Checks") if fault else f"What Does {label} Mean on a Samsung Washing Machine?"
  v.update({"title_tag":h1,"meta_description":(("Samsung washer won't drain? Safely check the hose and user-accessible filter and learn when service is required." if kind=='drain' else "Samsung washer won't spin? Safely check the load, level and drainage and learn when service is required.") if fault else f"Samsung washer showing {label}? Read the verified meaning, safe checks and when authorised service is required."),"h1":h1,"description":meaning[0].upper()+meaning[1:]+".","quick_fix":action+" (about 5–30 minutes).","intro_html":f"<p>{meaning[0].upper()+meaning[1:]}.</p><p>{action}. Open no panels, measure no internal parts and do not order a part from the symptom alone.</p>","causes_json":[{"cause":x,"detail":"This is a possible cause; the exact model manual and professional diagnosis determine internal faults."} for x in causes],"steps_json":[{"step":1,"action":"Stop safely","detail":"Stop the programme, wait for the drum to stop and do not force the door."},{"step":2,"action":"Record the symptom","detail":"Photograph the display and note the model number, programme stage and visible symptoms."},{"step":3,"action":"Make safe external checks","detail":action+". Follow the exact manual when draining water or cleaning a filter."},{"step":4,"action":"Test once","detail":"Test only after correcting an external cause, and never with leakage, burning smell, smoke, abnormal heat or electrical damage."},{"step":5,"action":"Arrange Samsung service","detail":"Request service if the fault remains or returns. Dismantle nothing and make no electrical measurements."}],"when_to_call_technician_html":"<p>Arrange Samsung service if the problem remains after safe external checks. Sensors, motors, fans, pumps, valves, wiring and electronics are not user repairs.</p><p>Unplug immediately for leakage near electricity, burning smell, smoke, sparks, abnormal heat or tripped protection.</p>","prevention_html":"<p>Follow load and detergent instructions, keep the washer level and inspect visible hoses and user-accessible filters as the exact manual specifies.</p><p>Internal sensor, motor, pump, fan, valve and electronics faults cannot be prevented through dismantling.</p>","faq_json":faqs("won't drain" if kind=='drain' else "won't spin" if kind=='spin' else label,action,False,fault)})
 v['parts_json']=[];assert len(v['title_tag'])<=70 and len(v['meta_description'])<=165;return v

def main():
 b=json.loads((BASE_DIR/'data/backups/article_reviews/batch-028-samsung-overflow-system-temperature-faults-before.json').read_text(encoding='utf-8'));rows={(r['article_id'],r['locale']):r for r in b['rows']};o={"batch":"028-samsung-overflow-system-temperature-faults","status":"proposal_only_not_applied","article_ids":list(ITEMS),"sources":["https://www.samsung.com/ae/support/home-appliances/overflow-error-on-samsung-washing-machine/","https://www.samsung.com/us/support/troubleshoot/TSG10000997/","https://www.samsung.com/ua/support/home-appliances/how-to-solve-the-temperature-problem-of-my-washing-machine-error-codes-tc1-tc2/","https://www.samsung.com/us/support/troubleshoot/TSG10007110/","https://www.samsung.com/uk/support/home-appliances/what-to-do-if-your-washing-machine-is-not-spinning/"],"translations":{}}
 for i,(label,kind) in ITEMS.items():o['translations'][str(i)]={"code":label,"preserve":{"en_slug":rows[(i,'en')]['slug'],"sv_slug":rows[(i,'sv')]['slug']},"en":make(i,False),"sv":make(i,True)}
 p=BASE_DIR/'data/article_reviews/batch-028-samsung-overflow-system-temperature-faults-proposal.json';p.write_text(json.dumps(o,ensure_ascii=False,indent=2),encoding='utf-8');print(p)
if __name__=='__main__':main()
